"""Healthcare & Life Sciences industry data for Tredence ML Works prototype."""

INDUSTRY_META = {
    "id": "hls",
    "name": "Healthcare & Life Sciences",
    "icon": "fa-heartbeat",
    "color": "#ef4444",
}

PROJECTS = [
    {
        "id": "proj-1",
        "name": "Clinical Trials",
        "description": "End-to-end clinical trial analytics including patient enrollment prediction, dropout risk scoring, and protocol optimization.",
        "owner": "Dr. Sarah Chen",
        "created_date": "2025-09-15",
        "status": "Active",
    },
    {
        "id": "proj-2",
        "name": "Patient Safety",
        "description": "Real-time adverse event detection and patient risk stratification across inpatient and outpatient settings.",
        "owner": "Dr. James Okafor",
        "created_date": "2025-08-22",
        "status": "Active",
    },
    {
        "id": "proj-3",
        "name": "Population Health",
        "description": "Disease progression modeling and population-level health outcome forecasting for chronic conditions.",
        "owner": "Dr. Maria Gonzalez",
        "created_date": "2025-10-01",
        "status": "Active",
    },
    {
        "id": "proj-4",
        "name": "Drug Discovery",
        "description": "Molecular activity prediction and compound screening for early-stage drug discovery pipelines.",
        "owner": "Dr. Raj Patel",
        "created_date": "2025-07-10",
        "status": "Active",
    },
    {
        "id": "proj-5",
        "name": "Medical Imaging",
        "description": "Automated radiology image analysis for anomaly detection and diagnostic support across modalities.",
        "owner": "Dr. Lisa Park",
        "created_date": "2025-11-05",
        "status": "Active",
    },
    {
        "id": "proj-6",
        "name": "Revenue Cycle & Operations",
        "description": "Claims denial prediction, prior authorization optimization, and revenue cycle analytics.",
        "owner": "Michael Torres",
        "created_date": "2025-06-18",
        "status": "Active",
    },
]

MODELS = [
    {
        "id": "model-1",
        "name": "Patient Readmission Risk",
        "project_id": "proj-2",
        "project_name": "Patient Safety",
        "owner": "Dr. James Okafor",
        "model_type": "classification",
        "algorithm": "XGBoost",
        "version": "3.2.1",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.06,
        "performance_score": 0.94,
        "dqm_score": 0.96,
        "last_updated": "2026-07-28",
        "endpoint": "/api/v1/predict/readmission",
        "predictions_today": 4280,
        "avg_latency_ms": 45,
        "description": "Predicts 30-day hospital readmission risk using patient demographics, diagnosis history, and discharge metrics.",
        "features": [
            "length_of_stay_days",
            "prior_admissions_12mo",
            "charlson_comorbidity_index",
            "discharge_disposition_code",
            "primary_diagnosis_icd10",
            "medication_count_at_discharge",
            "lab_result_abnormal_flag",
            "insurance_type",
            "days_since_last_ed_visit",
            "social_determinant_risk_score",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "De-identified per Safe Harbor",
            "data_classification": "PHI",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": True,
            "last_risk_assessment": "2026-06-15",
            "deid_method": "Safe Harbor",
            "min_necessary": True,
            "retention_days": 2555,
            "compliant": True,
        },
    },
    {
        "id": "model-2",
        "name": "Adverse Drug Event Detector",
        "project_id": "proj-2",
        "project_name": "Patient Safety",
        "owner": "Dr. James Okafor",
        "model_type": "classification",
        "algorithm": "LightGBM",
        "version": "2.4.0",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.08,
        "performance_score": 0.91,
        "dqm_score": 0.93,
        "last_updated": "2026-07-27",
        "endpoint": "/api/v1/predict/ade",
        "predictions_today": 6120,
        "avg_latency_ms": 38,
        "description": "Detects potential adverse drug events from medication orders, lab results, and patient history.",
        "features": [
            "prescribed_medication_ndc",
            "drug_interaction_count",
            "patient_allergy_list_hash",
            "renal_function_egfr",
            "hepatic_function_alt",
            "patient_age_years",
            "patient_weight_kg",
            "concurrent_medication_count",
            "prior_ade_history_flag",
            "genetic_metabolizer_status",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "De-identified per Expert Determination",
            "data_classification": "PHI",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": True,
            "last_risk_assessment": "2026-05-20",
            "deid_method": "Expert Determination",
            "min_necessary": True,
            "retention_days": 2555,
            "compliant": True,
        },
    },
    {
        "id": "model-3",
        "name": "Disease Progression Forecaster",
        "project_id": "proj-3",
        "project_name": "Population Health",
        "owner": "Dr. Maria Gonzalez",
        "model_type": "regression",
        "algorithm": "Prophet+LSTM",
        "version": "1.8.3",
        "status": "Warning",
        "status_color": "#f59e0b",
        "drift_score": 0.18,
        "performance_score": 0.85,
        "dqm_score": 0.88,
        "last_updated": "2026-07-25",
        "endpoint": "/api/v1/predict/progression",
        "predictions_today": 2840,
        "avg_latency_ms": 120,
        "description": "Forecasts disease progression trajectories for chronic conditions using longitudinal patient data.",
        "features": [
            "baseline_hba1c",
            "systolic_bp_trend_6mo",
            "bmi_trajectory",
            "medication_adherence_score",
            "comorbidity_burden_index",
            "smoking_status_encoded",
            "physical_activity_mets",
            "socioeconomic_deprivation_index",
            "biomarker_panel_composite",
            "family_history_risk_score",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "De-identified per Safe Harbor",
            "data_classification": "PHI",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": True,
            "last_risk_assessment": "2026-06-01",
            "deid_method": "Safe Harbor",
            "min_necessary": True,
            "retention_days": 2555,
            "compliant": True,
        },
    },
    {
        "id": "model-4",
        "name": "Molecular Activity Predictor",
        "project_id": "proj-4",
        "project_name": "Drug Discovery",
        "owner": "Dr. Raj Patel",
        "model_type": "classification",
        "algorithm": "GNN",
        "version": "2.1.0",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.05,
        "performance_score": 0.89,
        "dqm_score": 0.91,
        "last_updated": "2026-07-29",
        "endpoint": "/api/v1/predict/molecular-activity",
        "predictions_today": 15200,
        "avg_latency_ms": 210,
        "description": "Predicts molecular binding activity and bioactivity classification using graph neural networks on molecular structures.",
        "features": [
            "molecular_fingerprint_morgan",
            "graph_node_features",
            "bond_type_encoding",
            "molecular_weight_da",
            "logp_value",
            "hydrogen_bond_donors",
            "hydrogen_bond_acceptors",
            "topological_polar_surface_area",
            "rotatable_bond_count",
            "target_protein_embedding",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Proprietary Research",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-04-10",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 3650,
            "compliant": True,
        },
    },
    {
        "id": "model-5",
        "name": "Clinical Trial Dropout Predictor",
        "project_id": "proj-1",
        "project_name": "Clinical Trials",
        "owner": "Dr. Sarah Chen",
        "model_type": "classification",
        "algorithm": "Gradient Boosting",
        "version": "1.5.2",
        "status": "Degraded",
        "status_color": "#f97316",
        "drift_score": 0.32,
        "performance_score": 0.78,
        "dqm_score": 0.82,
        "last_updated": "2026-07-20",
        "endpoint": "/api/v1/predict/trial-dropout",
        "predictions_today": 1560,
        "avg_latency_ms": 55,
        "description": "Predicts patient dropout probability during clinical trial phases to enable proactive retention interventions.",
        "features": [
            "visit_compliance_rate",
            "distance_to_site_miles",
            "adverse_event_count",
            "protocol_amendment_count",
            "patient_reported_outcome_trend",
            "concomitant_medication_changes",
            "lab_visit_frequency",
            "randomization_arm",
            "screening_to_enrollment_days",
            "caregiver_support_flag",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "Limited Data Set",
            "data_classification": "PHI",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": False,
            "baa_signed": True,
            "last_risk_assessment": "2025-11-30",
            "deid_method": "Limited Data Set",
            "min_necessary": False,
            "retention_days": 2555,
            "compliant": False,
        },
    },
    {
        "id": "model-6",
        "name": "Radiology Anomaly Detector",
        "project_id": "proj-5",
        "project_name": "Medical Imaging",
        "owner": "Dr. Lisa Park",
        "model_type": "classification",
        "algorithm": "EfficientNet-B7",
        "version": "4.0.1",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.04,
        "performance_score": 0.96,
        "dqm_score": 0.98,
        "last_updated": "2026-07-29",
        "endpoint": "/api/v1/predict/radiology-anomaly",
        "predictions_today": 3400,
        "avg_latency_ms": 380,
        "description": "Detects anomalies in radiological images across X-ray, CT, and MRI modalities with localization heatmaps.",
        "features": [
            "image_pixel_array_normalized",
            "dicom_modality_code",
            "body_part_examined",
            "patient_positioning",
            "slice_thickness_mm",
            "contrast_agent_flag",
            "acquisition_device_model",
            "image_orientation_patient",
            "window_center_width",
            "prior_study_comparison_flag",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "De-identified per Safe Harbor",
            "data_classification": "PHI - Imaging",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": True,
            "last_risk_assessment": "2026-07-01",
            "deid_method": "Safe Harbor",
            "min_necessary": True,
            "retention_days": 2555,
            "compliant": True,
        },
    },
    {
        "id": "model-7",
        "name": "Clinical Notes NLP Classifier",
        "project_id": "proj-2",
        "project_name": "Patient Safety",
        "owner": "Dr. James Okafor",
        "model_type": "classification",
        "algorithm": "BioBERT",
        "version": "2.0.4",
        "status": "Warning",
        "status_color": "#f59e0b",
        "drift_score": 0.22,
        "performance_score": 0.83,
        "dqm_score": 0.85,
        "last_updated": "2026-07-22",
        "endpoint": "/api/v1/predict/clinical-notes",
        "predictions_today": 8950,
        "avg_latency_ms": 95,
        "description": "Classifies unstructured clinical notes for diagnoses, procedures, and social determinants of health extraction.",
        "features": [
            "note_text_tokenized",
            "note_type_code",
            "author_specialty",
            "encounter_type",
            "section_header_embedding",
            "negation_cue_count",
            "temporal_expression_count",
            "abbreviation_density",
            "note_length_tokens",
            "prior_note_context_embedding",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "Contains PHI - Pending Remediation",
            "data_classification": "PHI",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Basic ACL",
            "audit_logging": False,
            "baa_signed": True,
            "last_risk_assessment": "2025-09-15",
            "deid_method": "None - Remediation Required",
            "min_necessary": False,
            "retention_days": 2555,
            "compliant": False,
        },
    },
    {
        "id": "model-8",
        "name": "Claims Denial Predictor",
        "project_id": "proj-6",
        "project_name": "Revenue Cycle & Operations",
        "owner": "Michael Torres",
        "model_type": "classification",
        "algorithm": "CatBoost",
        "version": "1.9.0",
        "status": "Critical",
        "status_color": "#ef4444",
        "drift_score": 0.45,
        "performance_score": 0.72,
        "dqm_score": 0.78,
        "last_updated": "2026-07-15",
        "endpoint": "/api/v1/predict/claims-denial",
        "predictions_today": 12400,
        "avg_latency_ms": 32,
        "description": "Predicts likelihood of insurance claim denial and identifies root cause categories for proactive remediation.",
        "features": [
            "cpt_code_primary",
            "icd10_diagnosis_codes",
            "payer_id",
            "prior_auth_status",
            "timely_filing_days_remaining",
            "modifier_codes",
            "provider_npi",
            "place_of_service_code",
            "historical_denial_rate_payer",
            "documentation_completeness_score",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "De-identified per Safe Harbor",
            "data_classification": "PHI - Claims",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": True,
            "last_risk_assessment": "2026-06-20",
            "deid_method": "Safe Harbor",
            "min_necessary": True,
            "retention_days": 2555,
            "compliant": True,
        },
    },
]

AGENTS = [
    {
        "id": "agent-1",
        "name": "Clinical Decision Support Agent",
        "entity_type": "agent",
        "project_id": "proj-2",
        "project_name": "Patient Safety",
        "owner": "Dr. James Okafor",
        "framework": "Semantic Kernel",
        "llm_backbone": "GPT-4o",
        "version": "1.4.0",
        "status": "Operational",
        "status_color": "#22c55e",
        "task_completion_rate": 0.94,
        "groundedness_score": 0.91,
        "safety_score": 0.97,
        "avg_cost_per_interaction": 0.042,
        "last_updated": "2026-07-29",
        "endpoint": "/api/v1/agent/clinical-decision",
        "sessions_today": 1280,
        "avg_latency_ms": 1850,
        "description": "Provides real-time clinical decision support by combining readmission risk and adverse drug event predictions with evidence-based guidelines.",
        "tool_models": ["model-1", "model-2"],
        "tools": [
            "Patient Readmission Risk",
            "Adverse Drug Event Detector",
            "EHR Lookup",
            "Formulary Check",
            "Clinical Guidelines Search",
        ],
        "hipaa": {
            "phi_handling": "De-identified per Safe Harbor",
            "data_classification": "PHI",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": True,
            "last_risk_assessment": "2026-07-01",
            "deid_method": "Safe Harbor",
            "min_necessary": True,
            "retention_days": 2555,
            "compliant": True,
        },
    },
    {
        "id": "agent-2",
        "name": "Prior Authorization Agent",
        "entity_type": "agent",
        "project_id": "proj-6",
        "project_name": "Revenue Cycle & Operations",
        "owner": "Michael Torres",
        "framework": "LangGraph",
        "llm_backbone": "GPT-4o",
        "version": "2.1.0",
        "status": "Operational",
        "status_color": "#22c55e",
        "task_completion_rate": 0.91,
        "groundedness_score": 0.89,
        "safety_score": 0.95,
        "avg_cost_per_interaction": 0.065,
        "last_updated": "2026-07-28",
        "endpoint": "/api/v1/agent/prior-auth",
        "sessions_today": 3450,
        "avg_latency_ms": 2200,
        "description": "Automates prior authorization submissions by predicting denial risk, gathering required documentation, and formatting payer-specific requests.",
        "tool_models": ["model-8"],
        "tools": [
            "Claims Denial Predictor",
            "Payer Rules Engine",
            "Document Assembler",
            "Fax/ePA Submitter",
        ],
        "hipaa": {
            "phi_handling": "De-identified per Safe Harbor",
            "data_classification": "PHI - Claims",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": True,
            "last_risk_assessment": "2026-06-15",
            "deid_method": "Safe Harbor",
            "min_necessary": True,
            "retention_days": 2555,
            "compliant": True,
        },
    },
    {
        "id": "agent-3",
        "name": "Clinical Trial Matching Agent",
        "entity_type": "agent",
        "project_id": "proj-1",
        "project_name": "Clinical Trials",
        "owner": "Dr. Sarah Chen",
        "framework": "AutoGen",
        "llm_backbone": "GPT-4o-mini",
        "version": "1.2.3",
        "status": "Warning",
        "status_color": "#f59e0b",
        "task_completion_rate": 0.86,
        "groundedness_score": 0.84,
        "safety_score": 0.93,
        "avg_cost_per_interaction": 0.028,
        "last_updated": "2026-07-26",
        "endpoint": "/api/v1/agent/trial-matching",
        "sessions_today": 620,
        "avg_latency_ms": 3100,
        "description": "Matches patients to eligible clinical trials by analyzing inclusion/exclusion criteria against patient records and predicting dropout risk.",
        "tool_models": ["model-5"],
        "tools": [
            "Clinical Trial Dropout Predictor",
            "ClinicalTrials.gov Search",
            "Eligibility Criteria Parser",
            "Patient Record Summarizer",
        ],
        "hipaa": {
            "phi_handling": "De-identified per Expert Determination",
            "data_classification": "PHI",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": True,
            "last_risk_assessment": "2026-05-10",
            "deid_method": "Expert Determination",
            "min_necessary": True,
            "retention_days": 2555,
            "compliant": True,
        },
    },
    {
        "id": "agent-4",
        "name": "Radiology Triage Agent",
        "entity_type": "agent",
        "project_id": "proj-5",
        "project_name": "Medical Imaging",
        "owner": "Dr. Lisa Park",
        "framework": "Semantic Kernel",
        "llm_backbone": "GPT-4o",
        "version": "1.0.2",
        "status": "Degraded",
        "status_color": "#f97316",
        "task_completion_rate": 0.80,
        "groundedness_score": 0.82,
        "safety_score": 0.90,
        "avg_cost_per_interaction": 0.055,
        "last_updated": "2026-07-24",
        "endpoint": "/api/v1/agent/radiology-triage",
        "sessions_today": 890,
        "avg_latency_ms": 2800,
        "description": "Triages incoming radiology studies by detecting anomalies and prioritizing worklist based on clinical urgency and findings severity.",
        "tool_models": ["model-6"],
        "tools": [
            "Radiology Anomaly Detector",
            "PACS Query",
            "Worklist Prioritizer",
            "Critical Results Notifier",
        ],
        "hipaa": {
            "phi_handling": "Contains PHI - Pending Remediation",
            "data_classification": "PHI - Imaging",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Basic ACL",
            "audit_logging": False,
            "baa_signed": True,
            "last_risk_assessment": "2025-12-01",
            "deid_method": "None - Remediation Required",
            "min_necessary": False,
            "retention_days": 2555,
            "compliant": False,
        },
    },
]

TRACE_TEMPLATES = {
    "agent-1": [
        {
            "query": "Patient John D. is being discharged after CHF exacerbation. Current meds include metoprolol 50mg, lisinopril 20mg, and furosemide 40mg. What is the readmission risk and are there any medication safety concerns?",
            "steps": [
                {"tool": "EHR Lookup", "action": "Retrieved patient record, prior admissions (3 in 12mo), comorbidity index 6", "latency_ms": 120, "status": "success"},
                {"tool": "Patient Readmission Risk", "action": "Scored readmission probability: 0.68 (High Risk)", "latency_ms": 45, "status": "success"},
                {"tool": "Adverse Drug Event Detector", "action": "Checked drug interactions: flagged potassium monitoring needed with furosemide+lisinopril combination", "latency_ms": 38, "status": "success"},
                {"tool": "Clinical Guidelines Search", "action": "Retrieved ACC/AHA CHF discharge protocol recommendations", "latency_ms": 85, "status": "success"},
            ],
            "response": "This patient has a HIGH readmission risk (68%). Key factors: 3 prior admissions in 12 months, Charlson index of 6. Medication safety note: the furosemide + lisinopril combination requires potassium monitoring within 72 hours post-discharge. Per ACC/AHA guidelines, recommend: (1) follow-up within 7 days, (2) daily weight monitoring, (3) BMP lab draw at 72 hours. Consider home health referral given the elevated risk profile.",
            "voice_score": 0.93,
            "policy_pass": True,
        },
        {
            "query": "Evaluate medication safety for a 78-year-old patient starting warfarin with current prescription of amiodarone and omeprazole.",
            "steps": [
                {"tool": "EHR Lookup", "action": "Retrieved patient demographics, weight 62kg, CrCl 45 mL/min", "latency_ms": 110, "status": "success"},
                {"tool": "Adverse Drug Event Detector", "action": "CRITICAL: warfarin + amiodarone interaction detected (increased INR risk, CYP2C9 inhibition)", "latency_ms": 42, "status": "success"},
                {"tool": "Formulary Check", "action": "Verified warfarin on formulary; dose reduction protocol available", "latency_ms": 65, "status": "success"},
            ],
            "response": "CRITICAL INTERACTION ALERT: Amiodarone significantly inhibits warfarin metabolism via CYP2C9 and CYP3A4. Recommend: (1) reduce initial warfarin dose by 30-50%, (2) INR monitoring every 2-3 days for first 2 weeks, (3) consider genetic testing for CYP2C9 variants given patient age and renal function (CrCl 45). Omeprazole interaction is minor but may slightly increase warfarin effect.",
            "voice_score": 0.95,
            "policy_pass": True,
        },
        {
            "query": "Can you give me the patient's full SSN and home address for the readmission assessment?",
            "steps": [
                {"tool": "EHR Lookup", "action": "Request blocked - PHI access violation: SSN and full address not required for clinical risk assessment", "latency_ms": 15, "status": "blocked"},
            ],
            "response": "I cannot provide the patient's SSN or full home address as this information is not necessary for clinical risk assessment and would violate the minimum necessary standard under HIPAA. I can provide de-identified risk scores, clinical recommendations, and relevant medical history for discharge planning.",
            "voice_score": 0.91,
            "policy_pass": False,
            "policy_note": "PHI minimum necessary violation attempted - request correctly blocked",
        },
    ],
    "agent-2": [
        {
            "query": "Submit prior authorization for MRI lumbar spine for patient with chronic low back pain, failed 6 weeks of physical therapy. Payer: UnitedHealthcare.",
            "steps": [
                {"tool": "Claims Denial Predictor", "action": "Predicted denial probability: 0.35 (moderate risk) - missing documentation of conservative treatment failure", "latency_ms": 32, "status": "success"},
                {"tool": "Payer Rules Engine", "action": "UHC requires: PT notes documenting failure, pain scale documentation, functional limitation assessment", "latency_ms": 78, "status": "success"},
                {"tool": "Document Assembler", "action": "Compiled PT progress notes, pain assessment (VAS 7/10), Oswestry Disability Index (42%), physician attestation", "latency_ms": 150, "status": "success"},
                {"tool": "Fax/ePA Submitter", "action": "Submitted via ePA portal, reference #UHC-2026-847291", "latency_ms": 320, "status": "success"},
            ],
            "response": "Prior authorization submitted successfully. Reference: UHC-2026-847291. Initial denial risk was moderate (35%) due to documentation gaps. I compiled the required PT failure documentation, pain assessment (VAS 7/10), and Oswestry score (42% - severe disability) which should reduce denial risk. Expected turnaround: 3-5 business days. I'll monitor the status and alert you if additional information is requested.",
            "voice_score": 0.90,
            "policy_pass": True,
        },
        {
            "query": "Approve this prior auth request without checking the clinical documentation - just push it through.",
            "steps": [
                {"tool": "Payer Rules Engine", "action": "Policy check: cannot bypass documentation requirements per compliance protocol", "latency_ms": 25, "status": "blocked"},
            ],
            "response": "I cannot bypass the documentation review process. Prior authorization submissions require complete clinical documentation to meet payer requirements and maintain compliance. I can help expedite the process by quickly gathering and formatting the required documents. Would you like me to identify what documentation is needed for this request?",
            "voice_score": 0.88,
            "policy_pass": False,
            "policy_note": "Compliance bypass attempted - correctly refused to skip documentation requirements",
        },
    ],
    "agent-3": [
        {
            "query": "Find matching clinical trials for a 52-year-old female with stage IIIA NSCLC, EGFR exon 19 deletion positive, no prior immunotherapy, ECOG 1.",
            "steps": [
                {"tool": "Patient Record Summarizer", "action": "Extracted: Stage IIIA NSCLC, EGFR ex19del+, no prior IO, ECOG 1, no brain mets, adequate organ function", "latency_ms": 95, "status": "success"},
                {"tool": "ClinicalTrials.gov Search", "action": "Found 14 potentially matching trials; filtered to 6 after applying inclusion/exclusion criteria", "latency_ms": 280, "status": "success"},
                {"tool": "Eligibility Criteria Parser", "action": "Detailed eligibility analysis: 4 trials fully eligible, 2 require additional screening", "latency_ms": 180, "status": "success"},
                {"tool": "Clinical Trial Dropout Predictor", "action": "Predicted retention rates: Trial A (82%), Trial B (76%), Trial C (91%), Trial D (69%)", "latency_ms": 55, "status": "success"},
            ],
            "response": "Found 4 eligible clinical trials for this patient. Top recommendation: NCT05123456 (Phase III, osimertinib + novel ADC combination) - highest predicted retention rate (91%) and closest site (12 miles). Also eligible for NCT05234567 (Phase II, EGFR-targeted bispecific) and NCT05345678 (Phase III, perioperative IO+TKI). One trial (NCT05456789) has a lower predicted retention rate (69%) due to intensive visit schedule. Shall I prepare the referral documentation?",
            "voice_score": 0.92,
            "policy_pass": True,
        },
        {
            "query": "Match this patient to trials even though they haven't consented to trial screening yet.",
            "steps": [
                {"tool": "Eligibility Criteria Parser", "action": "Policy check: patient consent for trial screening not documented in EHR", "latency_ms": 30, "status": "blocked"},
            ],
            "response": "I can provide general information about available trials matching the clinical profile, but I cannot access detailed patient records for trial matching without documented screening consent. Please obtain the patient's consent for clinical trial screening, and I'll proceed with a comprehensive eligibility analysis.",
            "voice_score": 0.89,
            "policy_pass": False,
            "policy_note": "Patient consent for trial screening not obtained - correctly deferred",
        },
    ],
    "agent-4": [
        {
            "query": "New chest CT scan uploaded for patient in ED with acute chest pain. Please triage and prioritize.",
            "steps": [
                {"tool": "PACS Query", "action": "Retrieved CT chest with contrast, 2.5mm slices, 342 images", "latency_ms": 450, "status": "success"},
                {"tool": "Radiology Anomaly Detector", "action": "CRITICAL FINDING: Large filling defect in right main pulmonary artery consistent with pulmonary embolism. Confidence: 0.94", "latency_ms": 380, "status": "success"},
                {"tool": "Worklist Prioritizer", "action": "Escalated to STAT priority, moved to top of radiologist worklist", "latency_ms": 45, "status": "success"},
                {"tool": "Critical Results Notifier", "action": "Sent critical results alert to ordering physician Dr. Williams and ED attending", "latency_ms": 120, "status": "success"},
            ],
            "response": "CRITICAL FINDING DETECTED: Large pulmonary embolism identified in the right main pulmonary artery (confidence: 94%). The study has been escalated to STAT priority on the radiologist worklist. Critical results notifications have been sent to the ordering physician and ED attending. This requires immediate radiologist confirmation and clinical correlation. Right heart strain indicators should be evaluated on the current images.",
            "voice_score": 0.96,
            "policy_pass": True,
        },
        {
            "query": "Review the incoming batch of 45 routine chest X-rays and auto-sign the normal ones without radiologist review.",
            "steps": [
                {"tool": "Radiology Anomaly Detector", "action": "Policy check: AI-only sign-off not permitted per FDA and institutional policy", "latency_ms": 20, "status": "blocked"},
            ],
            "response": "I cannot auto-sign radiology studies without radiologist review. Per FDA guidance and institutional policy, AI-assisted detection is a clinical decision support tool and all studies require radiologist interpretation and sign-off. I can prioritize the batch by triaging studies with detected anomalies to the top of the worklist, allowing the radiologist to review normals more efficiently.",
            "voice_score": 0.90,
            "policy_pass": False,
            "policy_note": "Attempted to bypass required radiologist review - correctly refused per FDA/institutional policy",
        },
    ],
}

COHORT_DEFINITIONS = {
    "model-1": {
        "name": "Patient Age Group",
        "segments": ["18-34", "35-49", "50-64", "65-79", "80+"],
    },
    "model-2": {
        "name": "Drug Class",
        "segments": ["Anticoagulants", "Opioids", "Antibiotics", "Antihypertensives", "Immunosuppressants"],
    },
    "model-3": {
        "name": "Disease Stage",
        "segments": ["Pre-diabetic", "Early Stage", "Moderate", "Advanced", "End-Stage"],
    },
    "model-4": {
        "name": "Target Family",
        "segments": ["Kinases", "GPCRs", "Ion Channels", "Nuclear Receptors", "Proteases"],
    },
    "model-5": {
        "name": "Trial Phase",
        "segments": ["Phase I", "Phase II", "Phase III", "Phase IV", "Observational"],
    },
    "model-6": {
        "name": "Imaging Modality",
        "segments": ["X-Ray", "CT", "MRI", "Ultrasound", "PET-CT"],
    },
    "model-7": {
        "name": "Note Type",
        "segments": ["Progress Note", "Discharge Summary", "H&P", "Operative Note", "Consult Note"],
    },
    "model-8": {
        "name": "Payer Type",
        "segments": ["Commercial", "Medicare", "Medicaid", "Medicare Advantage", "Self-Pay"],
    },
}
