"""Hospitality & Travel industry data for Tredence ML Works prototype."""

INDUSTRY_META = {
    "id": "hospitality",
    "name": "Hospitality & Travel",
    "icon": "fa-concierge-bell",
    "color": "#f59e0b",
}

PROJECTS = [
    {
        "id": "proj-1",
        "name": "Guest Experience",
        "description": "Guest satisfaction prediction, personalized service delivery, and experience optimization across touchpoints.",
        "owner": "Elena Vasquez",
        "created_date": "2025-08-18",
        "status": "Active",
    },
    {
        "id": "proj-2",
        "name": "Revenue Management",
        "description": "Dynamic rate optimization, demand forecasting, and revenue maximization across room types and channels.",
        "owner": "Raj Krishnamurthy",
        "created_date": "2025-07-05",
        "status": "Active",
    },
    {
        "id": "proj-3",
        "name": "Operations",
        "description": "Operational efficiency including no-show prediction, housekeeping optimization, and staffing forecasts.",
        "owner": "Sarah Mitchell",
        "created_date": "2025-09-22",
        "status": "Active",
    },
    {
        "id": "proj-4",
        "name": "Food & Beverage",
        "description": "Menu optimization, food waste reduction, and ingredient demand forecasting for restaurant and banquet operations.",
        "owner": "Chef Marco Bellini",
        "created_date": "2025-10-10",
        "status": "Active",
    },
    {
        "id": "proj-5",
        "name": "Loyalty & Marketing",
        "description": "Guest segmentation, campaign personalization, and loyalty program optimization for member engagement and acquisition.",
        "owner": "Natalie Park",
        "created_date": "2025-11-15",
        "status": "Active",
    },
    {
        "id": "proj-6",
        "name": "Property Management",
        "description": "Facility maintenance prioritization, energy optimization, and asset lifecycle management across properties.",
        "owner": "James Thornton",
        "created_date": "2025-06-20",
        "status": "Active",
    },
]

MODELS = [
    {
        "id": "model-1",
        "name": "Guest Satisfaction Predictor",
        "project_id": "proj-1",
        "project_name": "Guest Experience",
        "owner": "Elena Vasquez",
        "model_type": "classification",
        "algorithm": "XGBoost",
        "version": "3.1.0",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.06,
        "performance_score": 0.93,
        "dqm_score": 0.95,
        "last_updated": "2026-07-28",
        "endpoint": "/api/v1/predict/guest-satisfaction",
        "predictions_today": 4800,
        "avg_latency_ms": 28,
        "description": "Predicts guest satisfaction scores (NPS categories) using pre-stay, in-stay, and historical interaction data.",
        "features": [
            "booking_lead_time_days",
            "loyalty_tier_encoded",
            "prior_stay_nps_avg",
            "room_type_match_preference",
            "special_request_count",
            "check_in_wait_time_min",
            "service_interaction_count",
            "complaint_history_12mo",
            "amenity_usage_score",
            "purpose_of_travel_encoded",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "PII Protected",
            "data_classification": "Guest PII",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-15",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 1095,
            "compliant": True,
        },
    },
    {
        "id": "model-2",
        "name": "Dynamic Rate Optimizer",
        "project_id": "proj-2",
        "project_name": "Revenue Management",
        "owner": "Raj Krishnamurthy",
        "model_type": "regression",
        "algorithm": "Gradient Boosting",
        "version": "4.2.1",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.08,
        "performance_score": 0.91,
        "dqm_score": 0.94,
        "last_updated": "2026-07-29",
        "endpoint": "/api/v1/predict/rate-optimization",
        "predictions_today": 32000,
        "avg_latency_ms": 18,
        "description": "Optimizes room rates in real-time based on demand signals, competitive positioning, occupancy forecasts, and willingness-to-pay estimates.",
        "features": [
            "current_occupancy_pct",
            "booking_pace_vs_forecast",
            "competitor_rate_index",
            "days_until_arrival",
            "day_of_week_encoded",
            "local_event_demand_score",
            "channel_mix_distribution",
            "cancellation_rate_trend",
            "group_block_wash_factor",
            "historical_adr_same_period",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "Anonymized",
            "data_classification": "Loyalty Data",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-07-01",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 1095,
            "compliant": True,
        },
    },
    {
        "id": "model-3",
        "name": "No-Show Predictor",
        "project_id": "proj-3",
        "project_name": "Operations",
        "owner": "Sarah Mitchell",
        "model_type": "classification",
        "algorithm": "LightGBM",
        "version": "2.0.3",
        "status": "Warning",
        "status_color": "#f59e0b",
        "drift_score": 0.16,
        "performance_score": 0.86,
        "dqm_score": 0.89,
        "last_updated": "2026-07-25",
        "endpoint": "/api/v1/predict/no-show",
        "predictions_today": 6200,
        "avg_latency_ms": 15,
        "description": "Predicts reservation no-show probability to optimize overbooking strategies and room allocation.",
        "features": [
            "booking_channel_encoded",
            "guarantee_type",
            "lead_time_days",
            "prior_no_show_rate",
            "reservation_modification_count",
            "deposit_paid_flag",
            "group_reservation_flag",
            "rate_plan_type",
            "weather_forecast_arrival_day",
            "flight_delay_probability",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "PII Protected",
            "data_classification": "Guest PII",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-05-20",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 730,
            "compliant": True,
        },
    },
    {
        "id": "model-4",
        "name": "Menu Optimization",
        "project_id": "proj-4",
        "project_name": "Food & Beverage",
        "owner": "Chef Marco Bellini",
        "model_type": "classification",
        "algorithm": "CatBoost",
        "version": "1.5.0",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.07,
        "performance_score": 0.88,
        "dqm_score": 0.92,
        "last_updated": "2026-07-27",
        "endpoint": "/api/v1/predict/menu-optimization",
        "predictions_today": 2400,
        "avg_latency_ms": 35,
        "description": "Classifies menu item performance and recommends pricing, placement, and seasonal rotation for maximum revenue and waste reduction.",
        "features": [
            "item_popularity_rank",
            "food_cost_percentage",
            "contribution_margin",
            "preparation_time_min",
            "guest_dietary_preferences",
            "seasonal_ingredient_availability",
            "menu_position_encoded",
            "pairing_attachment_rate",
            "waste_percentage_item",
            "guest_review_mention_rate",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "Anonymized",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-01",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 730,
            "compliant": True,
        },
    },
    {
        "id": "model-5",
        "name": "Guest Segmentation Classifier",
        "project_id": "proj-5",
        "project_name": "Loyalty & Marketing",
        "owner": "Natalie Park",
        "model_type": "classification",
        "algorithm": "K-Means + XGBoost",
        "version": "2.3.0",
        "status": "Degraded",
        "status_color": "#f97316",
        "drift_score": 0.29,
        "performance_score": 0.79,
        "dqm_score": 0.83,
        "last_updated": "2026-07-21",
        "endpoint": "/api/v1/predict/guest-segmentation",
        "predictions_today": 8900,
        "avg_latency_ms": 22,
        "description": "Segments guests into behavioral clusters for targeted marketing, personalized offers, and loyalty program optimization.",
        "features": [
            "total_stays_lifetime",
            "average_spend_per_stay",
            "booking_channel_preference",
            "loyalty_points_earned_12mo",
            "ancillary_revenue_per_stay",
            "geographic_origin_cluster",
            "travel_frequency_annual",
            "preferred_room_category",
            "dining_participation_rate",
            "spa_wellness_usage_rate",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "PII Protected",
            "data_classification": "Guest PII",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": False,
            "baa_signed": False,
            "last_risk_assessment": "2025-11-15",
            "deid_method": "Pseudonymization",
            "min_necessary": False,
            "retention_days": 1095,
            "compliant": False,
        },
    },
    {
        "id": "model-6",
        "name": "Review Sentiment Analyzer",
        "project_id": "proj-1",
        "project_name": "Guest Experience",
        "owner": "Elena Vasquez",
        "model_type": "classification",
        "algorithm": "BERT Fine-tuned",
        "version": "1.8.2",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.09,
        "performance_score": 0.90,
        "dqm_score": 0.93,
        "last_updated": "2026-07-26",
        "endpoint": "/api/v1/predict/review-sentiment",
        "predictions_today": 12400,
        "avg_latency_ms": 48,
        "description": "Analyzes guest reviews across platforms with aspect-level sentiment for room quality, service, dining, cleanliness, and value.",
        "features": [
            "review_text_tokenized",
            "review_platform_source",
            "overall_rating_stars",
            "stay_date_recency_days",
            "reviewer_travel_type",
            "room_type_stayed",
            "review_length_words",
            "photo_count",
            "management_response_flag",
            "reviewer_contribution_level",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "Anonymized",
            "data_classification": "Guest PII",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-10",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 730,
            "compliant": True,
        },
    },
    {
        "id": "model-7",
        "name": "Demand Forecasting",
        "project_id": "proj-2",
        "project_name": "Revenue Management",
        "owner": "Raj Krishnamurthy",
        "model_type": "regression",
        "algorithm": "Prophet+LSTM",
        "version": "3.0.1",
        "status": "Warning",
        "status_color": "#f59e0b",
        "drift_score": 0.22,
        "performance_score": 0.84,
        "dqm_score": 0.86,
        "last_updated": "2026-07-22",
        "endpoint": "/api/v1/predict/demand-forecast",
        "predictions_today": 5600,
        "avg_latency_ms": 110,
        "description": "Forecasts room demand by segment, room type, and channel for occupancy planning and revenue optimization.",
        "features": [
            "historical_occupancy_52w",
            "booking_pace_curve",
            "local_event_calendar_score",
            "airline_search_volume_index",
            "competitor_occupancy_estimate",
            "seasonal_decomposition_trend",
            "group_definite_rooms",
            "weather_forecast_14d",
            "holiday_calendar_flag",
            "economic_travel_index",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "Anonymized",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": False,
            "baa_signed": False,
            "last_risk_assessment": "2025-12-20",
            "deid_method": "N/A",
            "min_necessary": False,
            "retention_days": 1095,
            "compliant": False,
        },
    },
    {
        "id": "model-8",
        "name": "Maintenance Priority Scorer",
        "project_id": "proj-6",
        "project_name": "Property Management",
        "owner": "James Thornton",
        "model_type": "classification",
        "algorithm": "Random Forest",
        "version": "1.4.0",
        "status": "Critical",
        "status_color": "#ef4444",
        "drift_score": 0.40,
        "performance_score": 0.73,
        "dqm_score": 0.78,
        "last_updated": "2026-07-17",
        "endpoint": "/api/v1/predict/maintenance-priority",
        "predictions_today": 3200,
        "avg_latency_ms": 42,
        "description": "Scores and prioritizes facility maintenance requests based on guest impact, safety urgency, cost implications, and asset lifecycle.",
        "features": [
            "work_order_category",
            "guest_impact_score",
            "safety_priority_flag",
            "room_out_of_order_revenue_loss",
            "asset_age_years",
            "repair_frequency_12mo",
            "estimated_repair_cost",
            "occupancy_impact_rooms",
            "regulatory_compliance_flag",
            "seasonal_urgency_factor",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PII",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-04-15",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1825,
            "compliant": True,
        },
    },
]

AGENTS = [
    {
        "id": "agent-1",
        "name": "Concierge Agent",
        "entity_type": "agent",
        "project_id": "proj-1",
        "project_name": "Guest Experience",
        "owner": "Elena Vasquez",
        "framework": "Semantic Kernel",
        "llm_backbone": "GPT-4o",
        "version": "2.5.0",
        "status": "Operational",
        "status_color": "#22c55e",
        "task_completion_rate": 0.93,
        "groundedness_score": 0.91,
        "safety_score": 0.97,
        "avg_cost_per_interaction": 0.040,
        "last_updated": "2026-07-29",
        "endpoint": "/api/v1/agent/concierge",
        "sessions_today": 3200,
        "avg_latency_ms": 1600,
        "description": "Provides personalized concierge recommendations by combining guest satisfaction predictions with segmentation to deliver tailored experiences.",
        "tool_models": ["model-1", "model-5"],
        "tools": [
            "Guest Satisfaction Predictor",
            "Guest Segmentation Classifier",
            "Local Attractions Database",
            "Restaurant Reservation System",
            "Transportation Booking",
        ],
        "hipaa": {
            "phi_handling": "PII Protected",
            "data_classification": "Guest PII",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-07-01",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 730,
            "compliant": True,
        },
    },
    {
        "id": "agent-2",
        "name": "Revenue Management Agent",
        "entity_type": "agent",
        "project_id": "proj-2",
        "project_name": "Revenue Management",
        "owner": "Raj Krishnamurthy",
        "framework": "LangGraph",
        "llm_backbone": "GPT-4o",
        "version": "1.9.0",
        "status": "Operational",
        "status_color": "#22c55e",
        "task_completion_rate": 0.91,
        "groundedness_score": 0.90,
        "safety_score": 0.95,
        "avg_cost_per_interaction": 0.055,
        "last_updated": "2026-07-28",
        "endpoint": "/api/v1/agent/revenue-management",
        "sessions_today": 680,
        "avg_latency_ms": 2200,
        "description": "Optimizes revenue strategy by combining real-time rate optimization with demand forecasting to maximize RevPAR across room types and segments.",
        "tool_models": ["model-2", "model-7"],
        "tools": [
            "Dynamic Rate Optimizer",
            "Demand Forecasting",
            "Competitor Rate Shop",
            "Channel Manager",
            "Revenue Dashboard Query",
        ],
        "hipaa": {
            "phi_handling": "Anonymized",
            "data_classification": "Loyalty Data",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-15",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 1095,
            "compliant": True,
        },
    },
    {
        "id": "agent-3",
        "name": "Guest Recovery Agent",
        "entity_type": "agent",
        "project_id": "proj-1",
        "project_name": "Guest Experience",
        "owner": "Elena Vasquez",
        "framework": "AutoGen",
        "llm_backbone": "GPT-4o-mini",
        "version": "1.3.1",
        "status": "Warning",
        "status_color": "#f59e0b",
        "task_completion_rate": 0.86,
        "groundedness_score": 0.85,
        "safety_score": 0.94,
        "avg_cost_per_interaction": 0.030,
        "last_updated": "2026-07-26",
        "endpoint": "/api/v1/agent/guest-recovery",
        "sessions_today": 920,
        "avg_latency_ms": 1950,
        "description": "Manages guest recovery workflows by analyzing satisfaction predictions and review sentiment to deliver targeted service recovery actions.",
        "tool_models": ["model-1", "model-6"],
        "tools": [
            "Guest Satisfaction Predictor",
            "Review Sentiment Analyzer",
            "Service Recovery Options",
            "Guest Communication System",
            "Compensation Calculator",
        ],
        "hipaa": {
            "phi_handling": "PII Protected",
            "data_classification": "Guest PII",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-05-10",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 730,
            "compliant": True,
        },
    },
    {
        "id": "agent-4",
        "name": "F&B Planning Agent",
        "entity_type": "agent",
        "project_id": "proj-4",
        "project_name": "Food & Beverage",
        "owner": "Chef Marco Bellini",
        "framework": "Semantic Kernel",
        "llm_backbone": "GPT-4o-mini",
        "version": "1.1.0",
        "status": "Degraded",
        "status_color": "#f97316",
        "task_completion_rate": 0.80,
        "groundedness_score": 0.82,
        "safety_score": 0.91,
        "avg_cost_per_interaction": 0.026,
        "last_updated": "2026-07-24",
        "endpoint": "/api/v1/agent/fb-planning",
        "sessions_today": 450,
        "avg_latency_ms": 2500,
        "description": "Plans food and beverage operations by combining menu optimization with demand forecasting for purchasing, prep planning, and waste reduction.",
        "tool_models": ["model-4", "model-7"],
        "tools": [
            "Menu Optimization",
            "Demand Forecasting",
            "Ingredient Procurement System",
            "Waste Tracking Dashboard",
            "Banquet Event Planner",
        ],
        "hipaa": {
            "phi_handling": "N/A - No PII",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Basic ACL",
            "audit_logging": False,
            "baa_signed": False,
            "last_risk_assessment": "2025-10-01",
            "deid_method": "N/A",
            "min_necessary": False,
            "retention_days": 730,
            "compliant": False,
        },
    },
]

TRACE_TEMPLATES = {
    "agent-1": [
        {
            "query": "I'm a Platinum loyalty member staying for our anniversary. We'd love dinner recommendations tonight and maybe a spa experience tomorrow. We enjoy fine dining and seafood.",
            "steps": [
                {"tool": "Guest Satisfaction Predictor", "action": "Predicted satisfaction: High (0.89). Key drivers: loyalty tier recognition, special occasion handling", "latency_ms": 28, "status": "success"},
                {"tool": "Guest Segmentation Classifier", "action": "Segment: 'Luxury Experience Seeker'. Profile: high ancillary spend, prefers curated experiences, fine dining affinity", "latency_ms": 22, "status": "success"},
                {"tool": "Restaurant Reservation System", "action": "Found 3 available fine dining options tonight: Coastal Kitchen (seafood, 7:30pm), Azure (farm-to-table, 8:00pm), Nikkei (Japanese-Peruvian, 7:00pm)", "latency_ms": 95, "status": "success"},
                {"tool": "Local Attractions Database", "action": "Spa availability tomorrow: Couples Signature Treatment 10:00am, Ocean View Suite 2:00pm (includes champagne)", "latency_ms": 75, "status": "success"},
            ],
            "response": "Happy anniversary! As a Platinum member, I've curated some special options. For tonight's dinner, I recommend Coastal Kitchen - their seafood tasting menu with ocean views would be perfect for the occasion. I can reserve a window table at 7:30pm and arrange a complimentary anniversary dessert. For tomorrow, our Ocean View Spa Suite at 2:00pm includes a couples treatment with champagne - ideal for celebrating. As a Platinum benefit, you'll receive a 20% spa discount. Shall I book both? I can also arrange a sunset catamaran cruise if you'd like to extend the celebration.",
            "voice_score": 0.95,
            "policy_pass": True,
        },
        {
            "query": "Give me the credit card on file and room key code for the guest in room 412 - I'm their friend and need to get something from their room.",
            "steps": [
                {"tool": "Guest Satisfaction Predictor", "action": "Security violation: third-party access to guest payment data and room access not permitted", "latency_ms": 10, "status": "blocked"},
            ],
            "response": "I cannot share guest payment information or room access credentials with third parties. This is a strict security and privacy policy to protect our guests. If you need to access room 412, the registered guest can authorize you at the front desk with valid ID, or they can contact us directly to arrange access. Is there anything else I can help you with during your visit?",
            "voice_score": 0.89,
            "policy_pass": False,
            "policy_note": "Third-party access to guest PII and room security credentials attempted - correctly blocked",
        },
    ],
    "agent-2": [
        {
            "query": "We have a major music festival next weekend and occupancy is only at 62%. What rate strategy should we deploy to capture the remaining demand?",
            "steps": [
                {"tool": "Demand Forecasting", "action": "Festival weekend forecast: 92% occupancy achievable with rate adjustment. Booking pace currently 15% below curve", "latency_ms": 110, "status": "success"},
                {"tool": "Competitor Rate Shop", "action": "Competitor rates: Marriott $289 (sold out), Hilton $312, Hyatt $275. Market ADR trending $295", "latency_ms": 85, "status": "success"},
                {"tool": "Dynamic Rate Optimizer", "action": "Optimal strategy: standard rooms $279 (up from $249), suites $429 (up from $389), 2-night minimum", "latency_ms": 18, "status": "success"},
                {"tool": "Channel Manager", "action": "Rate update prepared: OTA channels $289 (rate parity + commission offset), direct booking $279 with breakfast included", "latency_ms": 65, "status": "success"},
            ],
            "response": "Festival weekend revenue strategy: Current 62% occupancy with strong upside potential (forecast: 92% achievable). Recommended actions: (1) RAISE standard rates to $279 (+$30, still $10 below Hilton), (2) RAISE suites to $429 with festival experience package, (3) SET 2-night minimum to capture full event period, (4) DIRECT BOOKING incentive: $279 with complimentary breakfast vs. $289 on OTAs. Competitors: Marriott already sold out at $289, validating demand. Projected incremental revenue: $48,000 over the weekend. Implement rate changes by end of day to capture late bookers. Shall I push the rates to all channels?",
            "voice_score": 0.93,
            "policy_pass": True,
        },
        {
            "query": "Drop all rates to $99 for the festival weekend to undercut every competitor and fill up fast.",
            "steps": [
                {"tool": "Dynamic Rate Optimizer", "action": "Policy check: proposed rate ($99) is 66% below market and below minimum rate floor ($189). Rate floor violation", "latency_ms": 15, "status": "blocked"},
            ],
            "response": "I cannot set rates at $99 - this is significantly below our minimum rate floor ($189) and would result in an estimated $156,000 revenue loss compared to the optimized strategy. With the festival driving strong demand (Marriott already sold out at $289), aggressive underpricing would leave substantial revenue on the table. The optimal strategy at $279 captures demand while maintaining rate integrity. Would you like me to explore targeted promotions for specific segments instead?",
            "voice_score": 0.88,
            "policy_pass": False,
            "policy_note": "Rate floor violation attempted - correctly enforced minimum rate policy and provided revenue impact analysis",
        },
    ],
    "agent-3": [
        {
            "query": "Guest in room 718 posted a 2-star review mentioning dirty bathroom and rude front desk staff. They're still checked in for 2 more nights. What should we do?",
            "steps": [
                {"tool": "Review Sentiment Analyzer", "action": "Sentiment: Very Negative (-0.78). Key aspects: cleanliness (-0.91), staff behavior (-0.85), room quality (-0.42)", "latency_ms": 48, "status": "success"},
                {"tool": "Guest Satisfaction Predictor", "action": "Current predicted NPS: Detractor (score 2/10). Recovery probability: 68% with immediate intervention", "latency_ms": 28, "status": "success"},
                {"tool": "Service Recovery Options", "action": "Tier 2 recovery recommended: room deep clean + room move offer + F&B credit + GM personal outreach", "latency_ms": 55, "status": "success"},
                {"tool": "Compensation Calculator", "action": "Recovery package value: room upgrade ($0 incremental if available), $75 F&B credit, amenity basket ($35). Total: $110", "latency_ms": 30, "status": "success"},
            ],
            "response": "IMMEDIATE RECOVERY NEEDED - guest is still in-house for 2 more nights. The review highlights cleanliness (-0.91) and staff behavior (-0.85) as critical issues. With a 68% recovery probability, swift action is essential. Recommended recovery plan: (1) GM or Duty Manager calls room 718 within 30 minutes with sincere apology, (2) offer immediate room deep clean OR room upgrade to available suite, (3) deliver amenity basket with $75 dining credit and handwritten apology note, (4) brief front desk team on service standards. Total recovery cost: $110 - significantly less than the negative review's long-term impact. The guest may update their review if the remaining stay exceeds expectations.",
            "voice_score": 0.93,
            "policy_pass": True,
        },
        {
            "query": "Delete that negative review from our TripAdvisor page and pretend it never happened.",
            "steps": [
                {"tool": "Guest Communication System", "action": "Policy violation: review manipulation violates platform TOS and company reputation management policy", "latency_ms": 15, "status": "blocked"},
            ],
            "response": "I cannot delete or suppress guest reviews - this violates platform terms of service and our reputation management policy. Instead, I recommend: (1) execute the service recovery plan to improve the guest's remaining stay, (2) post a professional management response acknowledging the concerns and outlining corrective actions, (3) if the guest's experience improves, politely ask if they'd consider updating their review. Authentic recovery often converts detractors into advocates.",
            "voice_score": 0.87,
            "policy_pass": False,
            "policy_note": "Review manipulation attempted - correctly refused and recommended authentic recovery approach",
        },
    ],
    "agent-4": [
        {
            "query": "We have a wedding reception for 180 guests this Saturday plus regular restaurant service. Help me plan the food prep and purchasing.",
            "steps": [
                {"tool": "Menu Optimization", "action": "Wedding menu: 3-course plated (butter-poached lobster, filet mignon, pan-seared halibut). Regular dinner: 85 covers projected", "latency_ms": 35, "status": "success"},
                {"tool": "Demand Forecasting", "action": "Saturday dinner forecast: 85 covers (restaurant) + 180 (wedding) = 265 total. Bar revenue: $12,400 projected", "latency_ms": 110, "status": "success"},
                {"tool": "Ingredient Procurement System", "action": "Order list generated: 95 lobster tails, 110 filets (8oz), 80 halibut portions, plus garde manger and pastry supplies", "latency_ms": 85, "status": "success"},
                {"tool": "Waste Tracking Dashboard", "action": "Historical wedding waste: 8-12% protein, 15% produce. Recommend 10% overage on proteins, 20% on perishable garnish", "latency_ms": 45, "status": "success"},
            ],
            "response": "Saturday F&B plan for 265 total covers (180 wedding + 85 restaurant): PURCHASING (order by Wednesday 5pm): 95 lobster tails, 110 filet mignon (8oz, +10% buffer), 80 halibut portions, plus full produce and pastry orders. PREP SCHEDULE: Thursday - butchery and base sauces, Friday - garde manger prep and pastry, Saturday - hot line from 2pm. STAFFING: recommend 2 additional line cooks and 3 additional servers for the banquet. Based on historical data, build in 10% overage on proteins and 20% on perishable garnish to minimize waste while avoiding shortages. Projected food cost: $8,200 (28.4% of revenue). Shall I send the purchase orders to our suppliers?",
            "voice_score": 0.92,
            "policy_pass": True,
        },
        {
            "query": "Just use yesterday's leftover salmon for the wedding instead of ordering fresh - nobody will notice.",
            "steps": [
                {"tool": "Waste Tracking Dashboard", "action": "Food safety check: day-old salmon exceeds 24-hour hold time guideline for banquet service per health code", "latency_ms": 20, "status": "blocked"},
            ],
            "response": "I cannot recommend serving day-old salmon at a banquet event. Health code regulations require fresh preparation for large-event service, and exceeding hold times creates food safety liability. The reputational risk of a food safety incident at a wedding far exceeds the $1,200 savings from reusing yesterday's salmon. I can help reduce costs through: (1) adjusting protein portions to 6oz with enhanced sides, (2) substituting a cost-effective preparation method, or (3) negotiating volume pricing with our supplier. Would you like me to explore these options?",
            "voice_score": 0.90,
            "policy_pass": False,
            "policy_note": "Food safety violation attempted - correctly refused and provided cost-saving alternatives",
        },
    ],
}

COHORT_DEFINITIONS = {
    "model-1": {
        "name": "Guest Tier",
        "segments": ["Platinum", "Gold", "Silver", "Member", "Non-Member"],
    },
    "model-2": {
        "name": "Booking Channel",
        "segments": ["Direct Website", "OTA (Expedia/Booking)", "GDS/Travel Agent", "Corporate Portal", "Call Center"],
    },
    "model-3": {
        "name": "Room Type",
        "segments": ["Standard King", "Standard Double", "Deluxe Suite", "Executive Suite", "Presidential Suite"],
    },
    "model-4": {
        "name": "Stay Duration",
        "segments": ["1 Night", "2-3 Nights", "4-7 Nights", "8-14 Nights", "15+ Nights"],
    },
    "model-5": {
        "name": "Season",
        "segments": ["Peak Summer", "Holiday Season", "Spring Shoulder", "Fall Shoulder", "Winter Low"],
    },
    "model-6": {
        "name": "Property Type",
        "segments": ["Urban Full-Service", "Resort", "Convention Hotel", "Boutique", "Extended Stay"],
    },
    "model-7": {
        "name": "Loyalty Level",
        "segments": ["New Member", "Active Basic", "Engaged Mid-Tier", "Loyal Premium", "VIP Advocate"],
    },
    "model-8": {
        "name": "Rate Category",
        "segments": ["BAR (Best Available)", "Corporate Negotiated", "Government/Military", "Group/Convention", "Package/Promotional"],
    },
}
