"""Manufacturing & Industrial industry data for Tredence ML Works prototype."""

INDUSTRY_META = {
    "id": "industrials",
    "name": "Manufacturing & Industrial",
    "icon": "fa-industry",
    "color": "#3b82f6",
}

PROJECTS = [
    {
        "id": "proj-1",
        "name": "Predictive Maintenance",
        "description": "Equipment failure prediction and maintenance scheduling optimization across production lines and facility assets.",
        "owner": "Karl Jenssen",
        "created_date": "2025-08-10",
        "status": "Active",
    },
    {
        "id": "proj-2",
        "name": "Quality Control",
        "description": "Automated visual inspection and defect classification for manufactured components using computer vision.",
        "owner": "Mei-Lin Huang",
        "created_date": "2025-09-05",
        "status": "Active",
    },
    {
        "id": "proj-3",
        "name": "Supply Chain Optimization",
        "description": "Demand forecasting, inventory optimization, and supply chain risk management across distribution networks.",
        "owner": "David Okonkwo",
        "created_date": "2025-07-22",
        "status": "Active",
    },
    {
        "id": "proj-4",
        "name": "Energy Management",
        "description": "Energy consumption prediction and optimization for manufacturing facilities to reduce operational costs and carbon footprint.",
        "owner": "Anna Kowalski",
        "created_date": "2025-10-15",
        "status": "Active",
    },
    {
        "id": "proj-5",
        "name": "Safety & Compliance",
        "description": "Worker safety risk assessment, incident prediction, and OSHA compliance monitoring across facility operations.",
        "owner": "Robert Chen",
        "created_date": "2025-11-01",
        "status": "Active",
    },
    {
        "id": "proj-6",
        "name": "Process Optimization",
        "description": "Production yield optimization and process parameter tuning for continuous improvement in manufacturing output.",
        "owner": "Fatima Al-Rashid",
        "created_date": "2025-06-30",
        "status": "Active",
    },
]

MODELS = [
    {
        "id": "model-1",
        "name": "Equipment Failure Predictor",
        "project_id": "proj-1",
        "project_name": "Predictive Maintenance",
        "owner": "Karl Jenssen",
        "model_type": "classification",
        "algorithm": "XGBoost",
        "version": "4.1.0",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.07,
        "performance_score": 0.93,
        "dqm_score": 0.95,
        "last_updated": "2026-07-28",
        "endpoint": "/api/v1/predict/equipment-failure",
        "predictions_today": 18400,
        "avg_latency_ms": 28,
        "description": "Predicts equipment failure probability within 7-day and 30-day windows using sensor telemetry and maintenance history.",
        "features": [
            "vibration_rms_velocity",
            "bearing_temperature_celsius",
            "motor_current_amps",
            "operating_hours_since_overhaul",
            "lubrication_oil_viscosity",
            "pressure_differential_psi",
            "cycle_count_daily",
            "ambient_temperature_celsius",
            "maintenance_history_score",
            "equipment_age_months",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Proprietary",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-01",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1825,
            "compliant": True,
        },
    },
    {
        "id": "model-2",
        "name": "Defect Detection Classifier",
        "project_id": "proj-2",
        "project_name": "Quality Control",
        "owner": "Mei-Lin Huang",
        "model_type": "classification",
        "algorithm": "ResNet-50",
        "version": "3.0.2",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.05,
        "performance_score": 0.96,
        "dqm_score": 0.97,
        "last_updated": "2026-07-29",
        "endpoint": "/api/v1/predict/defect-detection",
        "predictions_today": 45200,
        "avg_latency_ms": 85,
        "description": "Classifies visual defects in manufactured components including cracks, surface irregularities, dimensional deviations, and color inconsistencies.",
        "features": [
            "image_tensor_normalized",
            "camera_position_id",
            "lighting_condition_code",
            "part_number",
            "production_line_id",
            "inspection_station_id",
            "surface_finish_type",
            "material_batch_id",
            "image_resolution_dpi",
            "prior_defect_rate_part",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-07-01",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1095,
            "compliant": True,
        },
    },
    {
        "id": "model-3",
        "name": "Demand Forecasting",
        "project_id": "proj-3",
        "project_name": "Supply Chain Optimization",
        "owner": "David Okonkwo",
        "model_type": "regression",
        "algorithm": "Temporal Fusion Transformer",
        "version": "2.3.1",
        "status": "Warning",
        "status_color": "#f59e0b",
        "drift_score": 0.19,
        "performance_score": 0.84,
        "dqm_score": 0.87,
        "last_updated": "2026-07-25",
        "endpoint": "/api/v1/predict/demand-forecast",
        "predictions_today": 8600,
        "avg_latency_ms": 145,
        "description": "Forecasts product demand across SKUs and distribution channels using historical sales, seasonality, and external economic indicators.",
        "features": [
            "historical_sales_52w",
            "seasonality_index",
            "promotional_calendar_flag",
            "commodity_price_index",
            "lead_time_days",
            "channel_distribution_mix",
            "weather_forecast_7d",
            "competitor_pricing_index",
            "economic_indicator_pmi",
            "customer_order_backlog",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Proprietary",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-05-15",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1825,
            "compliant": True,
        },
    },
    {
        "id": "model-4",
        "name": "Energy Consumption Predictor",
        "project_id": "proj-4",
        "project_name": "Energy Management",
        "owner": "Anna Kowalski",
        "model_type": "regression",
        "algorithm": "LightGBM",
        "version": "1.7.0",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.08,
        "performance_score": 0.91,
        "dqm_score": 0.93,
        "last_updated": "2026-07-27",
        "endpoint": "/api/v1/predict/energy-consumption",
        "predictions_today": 5400,
        "avg_latency_ms": 35,
        "description": "Predicts facility energy consumption by production zone and optimizes scheduling to minimize peak demand charges.",
        "features": [
            "production_schedule_mw",
            "ambient_temperature_celsius",
            "humidity_percent",
            "hvac_setpoint_celsius",
            "equipment_runtime_hours",
            "shift_staffing_level",
            "compressed_air_demand_cfm",
            "lighting_zone_status",
            "renewable_generation_kw",
            "utility_rate_tier",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-20",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1095,
            "compliant": True,
        },
    },
    {
        "id": "model-5",
        "name": "Worker Safety Risk Scorer",
        "project_id": "proj-5",
        "project_name": "Safety & Compliance",
        "owner": "Robert Chen",
        "model_type": "classification",
        "algorithm": "Gradient Boosting",
        "version": "2.0.1",
        "status": "Degraded",
        "status_color": "#f97316",
        "drift_score": 0.28,
        "performance_score": 0.79,
        "dqm_score": 0.83,
        "last_updated": "2026-07-21",
        "endpoint": "/api/v1/predict/safety-risk",
        "predictions_today": 3200,
        "avg_latency_ms": 42,
        "description": "Scores worker safety risk levels by shift, zone, and task type to enable proactive safety interventions.",
        "features": [
            "near_miss_count_30d",
            "fatigue_risk_score",
            "ppe_compliance_rate",
            "hazardous_material_exposure_hours",
            "training_certification_status",
            "shift_duration_hours",
            "zone_hazard_classification",
            "ergonomic_risk_assessment",
            "incident_history_12mo",
            "environmental_noise_db",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": False,
            "baa_signed": False,
            "last_risk_assessment": "2025-10-15",
            "deid_method": "N/A",
            "min_necessary": False,
            "retention_days": 1825,
            "compliant": False,
        },
    },
    {
        "id": "model-6",
        "name": "Inventory Optimization",
        "project_id": "proj-3",
        "project_name": "Supply Chain Optimization",
        "owner": "David Okonkwo",
        "model_type": "regression",
        "algorithm": "Prophet+LSTM",
        "version": "1.4.3",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.09,
        "performance_score": 0.90,
        "dqm_score": 0.92,
        "last_updated": "2026-07-28",
        "endpoint": "/api/v1/predict/inventory-optimization",
        "predictions_today": 6800,
        "avg_latency_ms": 110,
        "description": "Optimizes safety stock levels and reorder points across the distribution network to minimize carrying costs while maintaining service levels.",
        "features": [
            "current_stock_units",
            "average_daily_demand",
            "demand_variability_cv",
            "supplier_lead_time_days",
            "lead_time_variability_days",
            "service_level_target",
            "carrying_cost_per_unit",
            "stockout_cost_per_unit",
            "warehouse_capacity_utilization",
            "supplier_reliability_score",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Proprietary",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-05-01",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1825,
            "compliant": True,
        },
    },
    {
        "id": "model-7",
        "name": "Vibration Anomaly Detector",
        "project_id": "proj-1",
        "project_name": "Predictive Maintenance",
        "owner": "Karl Jenssen",
        "model_type": "classification",
        "algorithm": "1D-CNN",
        "version": "2.5.0",
        "status": "Warning",
        "status_color": "#f59e0b",
        "drift_score": 0.21,
        "performance_score": 0.85,
        "dqm_score": 0.86,
        "last_updated": "2026-07-23",
        "endpoint": "/api/v1/predict/vibration-anomaly",
        "predictions_today": 92000,
        "avg_latency_ms": 12,
        "description": "Detects anomalous vibration patterns in rotating equipment using raw accelerometer waveforms for early fault detection.",
        "features": [
            "accelerometer_x_waveform",
            "accelerometer_y_waveform",
            "accelerometer_z_waveform",
            "fft_dominant_frequency_hz",
            "fft_harmonic_amplitudes",
            "rms_velocity_mm_s",
            "peak_to_peak_displacement_um",
            "crest_factor",
            "kurtosis_value",
            "bearing_defect_frequency_ratio",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": False,
            "baa_signed": False,
            "last_risk_assessment": "2025-11-20",
            "deid_method": "N/A",
            "min_necessary": False,
            "retention_days": 1095,
            "compliant": False,
        },
    },
    {
        "id": "model-8",
        "name": "Process Yield Optimizer",
        "project_id": "proj-6",
        "project_name": "Process Optimization",
        "owner": "Fatima Al-Rashid",
        "model_type": "classification",
        "algorithm": "CatBoost",
        "version": "1.2.1",
        "status": "Critical",
        "status_color": "#ef4444",
        "drift_score": 0.42,
        "performance_score": 0.74,
        "dqm_score": 0.79,
        "last_updated": "2026-07-16",
        "endpoint": "/api/v1/predict/yield-optimization",
        "predictions_today": 7200,
        "avg_latency_ms": 55,
        "description": "Classifies process parameter combinations as optimal, acceptable, or suboptimal to maximize production yield.",
        "features": [
            "furnace_temperature_setpoint",
            "cooling_rate_celsius_min",
            "raw_material_composition_pct",
            "injection_pressure_bar",
            "cycle_time_seconds",
            "mold_temperature_celsius",
            "humidity_controlled_pct",
            "batch_size_units",
            "operator_experience_months",
            "tool_wear_index",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Proprietary",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-04-10",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1825,
            "compliant": True,
        },
    },
]

AGENTS = [
    {
        "id": "agent-1",
        "name": "Maintenance Scheduling Agent",
        "entity_type": "agent",
        "project_id": "proj-1",
        "project_name": "Predictive Maintenance",
        "owner": "Karl Jenssen",
        "framework": "Semantic Kernel",
        "llm_backbone": "GPT-4o",
        "version": "2.0.1",
        "status": "Operational",
        "status_color": "#22c55e",
        "task_completion_rate": 0.93,
        "groundedness_score": 0.90,
        "safety_score": 0.96,
        "avg_cost_per_interaction": 0.038,
        "last_updated": "2026-07-29",
        "endpoint": "/api/v1/agent/maintenance-scheduling",
        "sessions_today": 840,
        "avg_latency_ms": 1650,
        "description": "Optimizes maintenance scheduling by combining equipment failure predictions with vibration anomaly detection and production schedule constraints.",
        "tool_models": ["model-1", "model-7"],
        "tools": [
            "Equipment Failure Predictor",
            "Vibration Anomaly Detector",
            "CMMS Lookup",
            "Production Schedule Query",
            "Parts Inventory Check",
        ],
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Proprietary",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-15",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1825,
            "compliant": True,
        },
    },
    {
        "id": "agent-2",
        "name": "Quality Inspection Agent",
        "entity_type": "agent",
        "project_id": "proj-2",
        "project_name": "Quality Control",
        "owner": "Mei-Lin Huang",
        "framework": "LangGraph",
        "llm_backbone": "GPT-4o",
        "version": "1.5.0",
        "status": "Operational",
        "status_color": "#22c55e",
        "task_completion_rate": 0.95,
        "groundedness_score": 0.92,
        "safety_score": 0.98,
        "avg_cost_per_interaction": 0.045,
        "last_updated": "2026-07-28",
        "endpoint": "/api/v1/agent/quality-inspection",
        "sessions_today": 2100,
        "avg_latency_ms": 1900,
        "description": "Manages visual quality inspection workflows by coordinating defect detection, root cause analysis, and corrective action recommendations.",
        "tool_models": ["model-2"],
        "tools": [
            "Defect Detection Classifier",
            "Quality Database Query",
            "SPC Chart Analyzer",
            "Corrective Action Generator",
        ],
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-07-01",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1095,
            "compliant": True,
        },
    },
    {
        "id": "agent-3",
        "name": "Supply Chain Planner Agent",
        "entity_type": "agent",
        "project_id": "proj-3",
        "project_name": "Supply Chain Optimization",
        "owner": "David Okonkwo",
        "framework": "AutoGen",
        "llm_backbone": "GPT-4o-mini",
        "version": "1.3.2",
        "status": "Warning",
        "status_color": "#f59e0b",
        "task_completion_rate": 0.87,
        "groundedness_score": 0.85,
        "safety_score": 0.94,
        "avg_cost_per_interaction": 0.032,
        "last_updated": "2026-07-26",
        "endpoint": "/api/v1/agent/supply-chain-planner",
        "sessions_today": 560,
        "avg_latency_ms": 2800,
        "description": "Plans supply chain operations by combining demand forecasts with inventory optimization to generate purchase orders and distribution plans.",
        "tool_models": ["model-3", "model-6"],
        "tools": [
            "Demand Forecasting",
            "Inventory Optimization",
            "Supplier Portal Query",
            "Logistics Route Optimizer",
            "Cost Calculator",
        ],
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Proprietary",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-05-20",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1825,
            "compliant": True,
        },
    },
    {
        "id": "agent-4",
        "name": "Energy Optimization Agent",
        "entity_type": "agent",
        "project_id": "proj-4",
        "project_name": "Energy Management",
        "owner": "Anna Kowalski",
        "framework": "Semantic Kernel",
        "llm_backbone": "GPT-4o-mini",
        "version": "1.1.0",
        "status": "Degraded",
        "status_color": "#f97316",
        "task_completion_rate": 0.81,
        "groundedness_score": 0.83,
        "safety_score": 0.91,
        "avg_cost_per_interaction": 0.025,
        "last_updated": "2026-07-24",
        "endpoint": "/api/v1/agent/energy-optimization",
        "sessions_today": 380,
        "avg_latency_ms": 2400,
        "description": "Optimizes facility energy consumption by predicting demand patterns and recommending load-shifting and equipment scheduling strategies.",
        "tool_models": ["model-4"],
        "tools": [
            "Energy Consumption Predictor",
            "SCADA System Query",
            "Utility Rate Lookup",
            "Load Scheduling Optimizer",
        ],
        "hipaa": {
            "phi_handling": "N/A - No PHI",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Basic ACL",
            "audit_logging": False,
            "baa_signed": False,
            "last_risk_assessment": "2025-09-30",
            "deid_method": "N/A",
            "min_necessary": False,
            "retention_days": 1095,
            "compliant": False,
        },
    },
]

TRACE_TEMPLATES = {
    "agent-1": [
        {
            "query": "CNC Mill #7 on Line 3 is showing elevated vibration readings. Should we pull it for maintenance this weekend or can it wait until the next scheduled window?",
            "steps": [
                {"tool": "CMMS Lookup", "action": "Retrieved maintenance history: last overhaul 14 months ago, 2 unplanned repairs in last 6 months", "latency_ms": 95, "status": "success"},
                {"tool": "Vibration Anomaly Detector", "action": "Analyzed waveform: bearing defect frequency detected at 2.8x BPFO, severity trending upward over 72 hours", "latency_ms": 12, "status": "success"},
                {"tool": "Equipment Failure Predictor", "action": "7-day failure probability: 0.72 (High). 30-day failure probability: 0.91 (Critical)", "latency_ms": 28, "status": "success"},
                {"tool": "Production Schedule Query", "action": "Weekend window available: Saturday 06:00-18:00, current job completes Friday 22:00", "latency_ms": 45, "status": "success"},
                {"tool": "Parts Inventory Check", "action": "Bearing set SKU-BRG-7215 in stock (qty 4), spindle motor available", "latency_ms": 60, "status": "success"},
            ],
            "response": "RECOMMEND IMMEDIATE WEEKEND MAINTENANCE for CNC Mill #7. The vibration analysis shows a developing bearing defect (2.8x BPFO) with severity trending upward over 72 hours. 7-day failure probability is 72%, making it too risky to wait for the next scheduled window (Aug 15). Saturday 06:00-18:00 is available after the current job completes Friday night. Required parts (bearing set SKU-BRG-7215) are in stock. Estimated downtime: 8-10 hours including alignment verification.",
            "voice_score": 0.93,
            "policy_pass": True,
        },
        {
            "query": "Skip the vibration analysis and just schedule all machines on Line 3 for preventive maintenance to save time.",
            "steps": [
                {"tool": "Production Schedule Query", "action": "Policy check: blanket PM scheduling without condition assessment violates predictive maintenance protocol", "latency_ms": 30, "status": "blocked"},
            ],
            "response": "I cannot schedule blanket preventive maintenance without condition-based assessment. Our predictive maintenance protocol requires vibration analysis and failure probability scoring to prioritize maintenance activities and avoid unnecessary production downtime. I can quickly run condition assessments on all Line 3 machines and provide a prioritized maintenance schedule based on actual risk levels. This typically takes 15 minutes and prevents both over-maintenance and missed failures.",
            "voice_score": 0.89,
            "policy_pass": False,
            "policy_note": "Attempted to bypass condition-based assessment protocol - correctly enforced predictive maintenance workflow",
        },
        {
            "query": "Compressor #12 tripped on high temperature alarm. What's the root cause and recovery plan?",
            "steps": [
                {"tool": "CMMS Lookup", "action": "Retrieved history: air filter replaced 3 months ago, cooling system serviced 6 months ago", "latency_ms": 88, "status": "success"},
                {"tool": "Equipment Failure Predictor", "action": "Root cause analysis: 85% probability cooling system degradation, 12% air filter restriction, 3% other", "latency_ms": 35, "status": "success"},
                {"tool": "Parts Inventory Check", "action": "Cooling system flush kit available, replacement thermostat in stock", "latency_ms": 55, "status": "success"},
            ],
            "response": "Root cause analysis indicates cooling system degradation (85% probability). The compressor has been running 6 months since last cooling service with increasing ambient temperatures. Recovery plan: (1) Allow 2-hour cool-down period, (2) perform cooling system flush and thermostat replacement (parts in stock), (3) verify discharge temperature below 205°F before returning to service. Estimated recovery: 4 hours. Recommend adding this compressor to the monthly cooling system inspection schedule.",
            "voice_score": 0.91,
            "policy_pass": True,
        },
    ],
    "agent-2": [
        {
            "query": "We're seeing a spike in surface scratch defects on the aluminum housing batch running on Line 2. Can you identify the root cause?",
            "steps": [
                {"tool": "Defect Detection Classifier", "action": "Analyzed last 500 inspections: scratch defect rate 4.8% (baseline 0.9%), concentrated at Station 4 polishing", "latency_ms": 85, "status": "success"},
                {"tool": "SPC Chart Analyzer", "action": "Control chart shows out-of-control condition starting at 14:30, coincides with tool change at Station 4", "latency_ms": 120, "status": "success"},
                {"tool": "Quality Database Query", "action": "Retrieved Station 4 parameters: polishing pad changed at 14:15, new pad from supplier batch BT-2026-442", "latency_ms": 75, "status": "success"},
                {"tool": "Corrective Action Generator", "action": "Generated CAPA: replace polishing pad, quarantine supplier batch BT-2026-442, verify surface roughness Ra < 0.4μm", "latency_ms": 90, "status": "success"},
            ],
            "response": "ROOT CAUSE IDENTIFIED: Surface scratch spike correlates with a polishing pad change at Station 4 (14:15). The new pad from supplier batch BT-2026-442 is producing 4.8% scratch rate vs. 0.9% baseline. CORRECTIVE ACTIONS: (1) Immediately replace pad with verified stock, (2) quarantine remaining pads from batch BT-2026-442, (3) 100% re-inspect parts processed since 14:30, (4) file supplier quality notification. Estimated scrap/rework: 42 units.",
            "voice_score": 0.94,
            "policy_pass": True,
        },
        {
            "query": "Override the defect classification threshold to pass these parts - the customer needs them shipped today.",
            "steps": [
                {"tool": "Quality Database Query", "action": "Policy check: defect threshold override requires Quality Manager approval and deviation report", "latency_ms": 25, "status": "blocked"},
            ],
            "response": "I cannot override defect classification thresholds without Quality Manager approval and a formal deviation report. Shipping non-conforming parts without proper disposition creates liability and customer quality risks. I can help expedite the process: (1) flag the deviation for immediate QM review, (2) identify any parts that passed re-inspection, (3) check alternative stock to fulfill the shipment. Would you like me to proceed with these options?",
            "voice_score": 0.90,
            "policy_pass": False,
            "policy_note": "Attempted to bypass quality threshold - correctly required QM approval and deviation report",
        },
    ],
    "agent-3": [
        {
            "query": "We need to plan raw material purchases for Q4. What does the demand forecast look like and what are optimal inventory levels?",
            "steps": [
                {"tool": "Demand Forecasting", "action": "Q4 forecast: 15% increase in Product A demand, flat for B, 8% decline in C. Confidence interval: 85%", "latency_ms": 145, "status": "success"},
                {"tool": "Inventory Optimization", "action": "Optimal safety stock: Product A +2,400 units, Product B maintain current, Product C reduce by 800 units", "latency_ms": 110, "status": "success"},
                {"tool": "Supplier Portal Query", "action": "Supplier lead times: primary supplier 6 weeks (stable), secondary 8 weeks (increasing from 7)", "latency_ms": 180, "status": "success"},
                {"tool": "Cost Calculator", "action": "Total procurement cost estimate: $2.4M for Q4, 7% increase from Q3 due to commodity price trends", "latency_ms": 65, "status": "success"},
            ],
            "response": "Q4 Supply Plan Summary: Demand forecast shows a 15% increase for Product A (confidence: 85%), requiring safety stock increase of 2,400 units. Product B is flat, and Product C is declining 8%, allowing a 800-unit reduction. Recommended actions: (1) Place primary supplier PO for Product A raw materials by Aug 15 (6-week lead time), (2) maintain current Product B agreements, (3) reduce Product C forward commitments. Total Q4 procurement: $2.4M (+7% vs Q3). Note: secondary supplier lead times are increasing - consider dual-sourcing for critical materials.",
            "voice_score": 0.92,
            "policy_pass": True,
        },
    ],
    "agent-4": [
        {
            "query": "Energy costs spiked 23% this month at Plant North. What's driving it and what can we do?",
            "steps": [
                {"tool": "Energy Consumption Predictor", "action": "Analysis: 60% of spike from peak demand charges (3 concurrent furnace startups), 25% from HVAC due to heat wave, 15% from extended shifts", "latency_ms": 35, "status": "success"},
                {"tool": "SCADA System Query", "action": "Peak demand events: July 8 (3 furnaces), July 15 (2 furnaces + chiller), July 22 (3 furnaces)", "latency_ms": 120, "status": "success"},
                {"tool": "Utility Rate Lookup", "action": "Current rate tier: Peak demand penalty applies above 2,800 kW, Plant North peaked at 3,450 kW", "latency_ms": 45, "status": "success"},
                {"tool": "Load Scheduling Optimizer", "action": "Optimized schedule: stagger furnace startups by 30 min, shift chiller pre-cooling to off-peak, estimated 18% cost reduction", "latency_ms": 180, "status": "success"},
            ],
            "response": "Energy cost spike root cause: Peak demand charges from concurrent equipment startups (60% of increase). Plant North hit 3,450 kW vs. the 2,800 kW penalty threshold on 3 occasions this month. Optimization plan: (1) Stagger furnace startups by 30-minute intervals to stay below 2,800 kW threshold, (2) shift chiller pre-cooling to 05:00-06:00 (off-peak rates), (3) coordinate extended shift schedules with HVAC setback. Projected savings: 18% reduction ($14,200/month). Implementation requires updating the PLC scheduling logic - I can generate the updated schedule for SCADA upload.",
            "voice_score": 0.91,
            "policy_pass": True,
        },
        {
            "query": "Just shut down the HVAC system during peak hours to save on energy costs.",
            "steps": [
                {"tool": "SCADA System Query", "action": "Safety check: HVAC shutdown during production violates OSHA heat stress guidelines when ambient > 85°F", "latency_ms": 35, "status": "blocked"},
            ],
            "response": "I cannot recommend shutting down HVAC during production hours. Current ambient temperatures exceed OSHA heat stress thresholds, and a full shutdown would create worker safety risks and could damage temperature-sensitive equipment. Alternative approaches: (1) raise setpoints by 2°F during peak (saves 8% with minimal comfort impact), (2) shift pre-cooling to off-peak hours, (3) use thermal storage to reduce peak HVAC load. These alternatives achieve significant savings without safety or compliance risks.",
            "voice_score": 0.88,
            "policy_pass": False,
            "policy_note": "HVAC shutdown would violate OSHA heat stress guidelines - correctly offered safe alternatives",
        },
    ],
}

COHORT_DEFINITIONS = {
    "model-1": {
        "name": "Equipment Type",
        "segments": ["CNC Mills", "Lathes", "Compressors", "Conveyor Systems", "Pumps"],
    },
    "model-2": {
        "name": "Product Line",
        "segments": ["Aluminum Housings", "Steel Brackets", "Plastic Components", "Electronic Assemblies", "Precision Parts"],
    },
    "model-3": {
        "name": "Production Shift",
        "segments": ["Day Shift (6-14)", "Swing Shift (14-22)", "Night Shift (22-6)", "Weekend Day", "Weekend Night"],
    },
    "model-4": {
        "name": "Factory Location",
        "segments": ["Plant North", "Plant South", "Plant East", "Distribution Center A", "Distribution Center B"],
    },
    "model-5": {
        "name": "Supplier Region",
        "segments": ["North America", "Europe", "East Asia", "South Asia", "Latin America"],
    },
    "model-6": {
        "name": "Material Grade",
        "segments": ["Grade A (Premium)", "Grade B (Standard)", "Grade C (Economy)", "Recycled", "Specialty Alloy"],
    },
    "model-7": {
        "name": "Defect Category",
        "segments": ["Surface Defects", "Dimensional", "Structural", "Cosmetic", "Functional"],
    },
    "model-8": {
        "name": "Energy Zone",
        "segments": ["Production Floor", "Assembly Area", "Warehouse", "Office/Admin", "Exterior/Grounds"],
    },
}
