"""Retail & E-Commerce industry data for Tredence ML Works prototype."""

INDUSTRY_META = {
    "id": "retail",
    "name": "Retail & E-Commerce",
    "icon": "fa-shopping-cart",
    "color": "#8b5cf6",
}

PROJECTS = [
    {
        "id": "proj-1",
        "name": "Customer Intelligence",
        "description": "Customer behavior analytics including churn prediction, lifetime value modeling, and segmentation for personalized engagement.",
        "owner": "Jessica Liu",
        "created_date": "2025-08-01",
        "status": "Active",
    },
    {
        "id": "proj-2",
        "name": "Merchandising",
        "description": "Product recommendation, assortment optimization, and visual search capabilities for omnichannel merchandising.",
        "owner": "Marcus Johnson",
        "created_date": "2025-09-12",
        "status": "Active",
    },
    {
        "id": "proj-3",
        "name": "Supply & Logistics",
        "description": "Demand forecasting, inventory replenishment, and logistics optimization across distribution centers and stores.",
        "owner": "Priya Sharma",
        "created_date": "2025-07-15",
        "status": "Active",
    },
    {
        "id": "proj-4",
        "name": "Pricing & Promotions",
        "description": "Dynamic pricing optimization, promotional effectiveness analysis, and competitive pricing intelligence.",
        "owner": "Tom O'Brien",
        "created_date": "2025-10-08",
        "status": "Active",
    },
    {
        "id": "proj-5",
        "name": "Store Operations",
        "description": "Fraud detection, loss prevention analytics, and store operations optimization for brick-and-mortar locations.",
        "owner": "Aisha Patel",
        "created_date": "2025-11-20",
        "status": "Active",
    },
    {
        "id": "proj-6",
        "name": "Digital Commerce",
        "description": "E-commerce conversion optimization, sentiment analysis, and visual search for enhanced online shopping experiences.",
        "owner": "Daniel Kim",
        "created_date": "2025-06-25",
        "status": "Active",
    },
]

MODELS = [
    {
        "id": "model-1",
        "name": "Customer Churn Predictor",
        "project_id": "proj-1",
        "project_name": "Customer Intelligence",
        "owner": "Jessica Liu",
        "model_type": "classification",
        "algorithm": "XGBoost",
        "version": "3.5.0",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.06,
        "performance_score": 0.92,
        "dqm_score": 0.95,
        "last_updated": "2026-07-28",
        "endpoint": "/api/v1/predict/churn",
        "predictions_today": 28400,
        "avg_latency_ms": 22,
        "description": "Predicts customer churn probability within 30, 60, and 90-day windows using transactional behavior and engagement signals.",
        "features": [
            "days_since_last_purchase",
            "purchase_frequency_90d",
            "average_order_value",
            "total_lifetime_spend",
            "email_open_rate_30d",
            "app_sessions_30d",
            "returns_rate_12mo",
            "loyalty_points_balance",
            "customer_service_contacts_90d",
            "browse_to_purchase_ratio",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "PII Protected",
            "data_classification": "Customer Data",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-10",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 1095,
            "compliant": True,
        },
    },
    {
        "id": "model-2",
        "name": "Product Recommendation Engine",
        "project_id": "proj-2",
        "project_name": "Merchandising",
        "owner": "Marcus Johnson",
        "model_type": "classification",
        "algorithm": "Deep Neural Network",
        "version": "5.1.2",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.07,
        "performance_score": 0.89,
        "dqm_score": 0.93,
        "last_updated": "2026-07-29",
        "endpoint": "/api/v1/predict/recommendations",
        "predictions_today": 156000,
        "avg_latency_ms": 18,
        "description": "Generates personalized product recommendations using collaborative filtering, content-based features, and contextual signals.",
        "features": [
            "user_embedding_128d",
            "item_embedding_128d",
            "browse_history_sequence",
            "purchase_history_encoded",
            "category_affinity_scores",
            "price_sensitivity_index",
            "seasonal_preference_vector",
            "contextual_time_features",
            "device_type_encoded",
            "social_proof_signal",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "Anonymized",
            "data_classification": "Customer Data",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-07-05",
            "deid_method": "Hashing",
            "min_necessary": True,
            "retention_days": 730,
            "compliant": True,
        },
    },
    {
        "id": "model-3",
        "name": "Demand Forecasting",
        "project_id": "proj-3",
        "project_name": "Supply & Logistics",
        "owner": "Priya Sharma",
        "model_type": "regression",
        "algorithm": "Prophet+LSTM",
        "version": "2.8.0",
        "status": "Warning",
        "status_color": "#f59e0b",
        "drift_score": 0.17,
        "performance_score": 0.86,
        "dqm_score": 0.89,
        "last_updated": "2026-07-25",
        "endpoint": "/api/v1/predict/demand",
        "predictions_today": 42000,
        "avg_latency_ms": 95,
        "description": "Forecasts product demand at SKU-store level using historical sales, seasonality, promotions, and external signals.",
        "features": [
            "historical_sales_52w",
            "promotional_uplift_factor",
            "seasonality_decomposition",
            "weather_impact_index",
            "local_event_calendar",
            "competitor_activity_flag",
            "price_change_history",
            "inventory_position",
            "new_product_launch_flag",
            "macro_economic_index",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "Anonymized",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-05-15",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1095,
            "compliant": True,
        },
    },
    {
        "id": "model-4",
        "name": "Dynamic Pricing Optimizer",
        "project_id": "proj-4",
        "project_name": "Pricing & Promotions",
        "owner": "Tom O'Brien",
        "model_type": "classification",
        "algorithm": "Gradient Boosting",
        "version": "2.2.1",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.09,
        "performance_score": 0.90,
        "dqm_score": 0.94,
        "last_updated": "2026-07-27",
        "endpoint": "/api/v1/predict/pricing",
        "predictions_today": 34000,
        "avg_latency_ms": 15,
        "description": "Classifies optimal price points by analyzing demand elasticity, competitive positioning, and margin targets across product categories.",
        "features": [
            "current_price",
            "competitor_price_ratio",
            "price_elasticity_estimate",
            "demand_velocity_7d",
            "inventory_weeks_of_supply",
            "margin_target_pct",
            "promotional_flag",
            "category_price_index",
            "customer_segment_mix",
            "channel_price_parity",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PII",
            "data_classification": "Proprietary",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-20",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1095,
            "compliant": True,
        },
    },
    {
        "id": "model-5",
        "name": "Fraud Detection Model",
        "project_id": "proj-5",
        "project_name": "Store Operations",
        "owner": "Aisha Patel",
        "model_type": "classification",
        "algorithm": "LightGBM",
        "version": "4.0.0",
        "status": "Degraded",
        "status_color": "#f97316",
        "drift_score": 0.31,
        "performance_score": 0.80,
        "dqm_score": 0.84,
        "last_updated": "2026-07-20",
        "endpoint": "/api/v1/predict/fraud",
        "predictions_today": 89000,
        "avg_latency_ms": 8,
        "description": "Detects fraudulent transactions in real-time using behavioral patterns, device fingerprinting, and transaction anomaly scoring.",
        "features": [
            "transaction_amount",
            "transaction_velocity_1h",
            "device_fingerprint_hash",
            "ip_geolocation_distance_km",
            "payment_method_risk_score",
            "account_age_days",
            "shipping_billing_mismatch",
            "time_since_last_transaction_min",
            "cart_composition_anomaly_score",
            "historical_chargeback_rate",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "PII Protected",
            "data_classification": "PII",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": False,
            "baa_signed": False,
            "last_risk_assessment": "2025-11-10",
            "deid_method": "Hashing",
            "min_necessary": False,
            "retention_days": 1095,
            "compliant": False,
        },
    },
    {
        "id": "model-6",
        "name": "Sentiment Analysis",
        "project_id": "proj-6",
        "project_name": "Digital Commerce",
        "owner": "Daniel Kim",
        "model_type": "classification",
        "algorithm": "BERT Fine-tuned",
        "version": "2.3.0",
        "status": "Healthy",
        "status_color": "#22c55e",
        "drift_score": 0.10,
        "performance_score": 0.88,
        "dqm_score": 0.91,
        "last_updated": "2026-07-26",
        "endpoint": "/api/v1/predict/sentiment",
        "predictions_today": 67000,
        "avg_latency_ms": 42,
        "description": "Classifies customer review and feedback sentiment with aspect-level granularity for product quality, delivery, and service dimensions.",
        "features": [
            "review_text_tokenized",
            "review_rating_stars",
            "review_length_words",
            "product_category_encoded",
            "verified_purchase_flag",
            "reviewer_history_count",
            "time_since_purchase_days",
            "helpfulness_votes_ratio",
            "image_attachment_flag",
            "response_from_seller_flag",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "Anonymized",
            "data_classification": "Customer Data",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-01",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 730,
            "compliant": True,
        },
    },
    {
        "id": "model-7",
        "name": "Inventory Replenishment",
        "project_id": "proj-3",
        "project_name": "Supply & Logistics",
        "owner": "Priya Sharma",
        "model_type": "regression",
        "algorithm": "Temporal Fusion Transformer",
        "version": "1.6.0",
        "status": "Warning",
        "status_color": "#f59e0b",
        "drift_score": 0.20,
        "performance_score": 0.83,
        "dqm_score": 0.87,
        "last_updated": "2026-07-23",
        "endpoint": "/api/v1/predict/replenishment",
        "predictions_today": 15800,
        "avg_latency_ms": 125,
        "description": "Predicts optimal replenishment quantities and timing across stores and distribution centers to minimize stockouts and overstock.",
        "features": [
            "current_on_hand_units",
            "sales_velocity_7d",
            "sales_velocity_28d",
            "store_capacity_utilization",
            "dc_to_store_lead_time_days",
            "promotional_calendar_weeks",
            "seasonal_demand_factor",
            "substitution_availability_flag",
            "markdown_schedule",
            "planogram_compliance_pct",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "N/A - No PII",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": False,
            "baa_signed": False,
            "last_risk_assessment": "2025-12-15",
            "deid_method": "N/A",
            "min_necessary": False,
            "retention_days": 1095,
            "compliant": False,
        },
    },
    {
        "id": "model-8",
        "name": "Visual Search Classifier",
        "project_id": "proj-6",
        "project_name": "Digital Commerce",
        "owner": "Daniel Kim",
        "model_type": "classification",
        "algorithm": "EfficientNet-B4",
        "version": "1.2.0",
        "status": "Critical",
        "status_color": "#ef4444",
        "drift_score": 0.38,
        "performance_score": 0.75,
        "dqm_score": 0.80,
        "last_updated": "2026-07-18",
        "endpoint": "/api/v1/predict/visual-search",
        "predictions_today": 12400,
        "avg_latency_ms": 180,
        "description": "Matches user-uploaded product images to catalog items for visual search and similar product discovery.",
        "features": [
            "image_embedding_512d",
            "color_histogram_features",
            "texture_descriptor",
            "shape_context_features",
            "brand_logo_detection_score",
            "product_category_prior",
            "image_quality_score",
            "background_complexity_score",
            "aspect_ratio",
            "dominant_color_rgb",
        ],
        "entity_type": "model",
        "hipaa": {
            "phi_handling": "Anonymized",
            "data_classification": "Customer Data",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-04-20",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 365,
            "compliant": True,
        },
    },
]

AGENTS = [
    {
        "id": "agent-1",
        "name": "Personal Shopping Assistant",
        "entity_type": "agent",
        "project_id": "proj-2",
        "project_name": "Merchandising",
        "owner": "Marcus Johnson",
        "framework": "Semantic Kernel",
        "llm_backbone": "GPT-4o",
        "version": "3.0.1",
        "status": "Operational",
        "status_color": "#22c55e",
        "task_completion_rate": 0.92,
        "groundedness_score": 0.89,
        "safety_score": 0.96,
        "avg_cost_per_interaction": 0.035,
        "last_updated": "2026-07-29",
        "endpoint": "/api/v1/agent/personal-shopper",
        "sessions_today": 8400,
        "avg_latency_ms": 1450,
        "description": "Provides personalized shopping assistance by combining product recommendations with churn risk assessment to drive engagement and retention.",
        "tool_models": ["model-2", "model-1"],
        "tools": [
            "Product Recommendation Engine",
            "Customer Churn Predictor",
            "Product Catalog Search",
            "Inventory Availability Check",
            "Promotion Lookup",
        ],
        "hipaa": {
            "phi_handling": "PII Protected",
            "data_classification": "Customer Data",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-07-01",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 730,
            "compliant": True,
        },
    },
    {
        "id": "agent-2",
        "name": "Pricing Strategy Agent",
        "entity_type": "agent",
        "project_id": "proj-4",
        "project_name": "Pricing & Promotions",
        "owner": "Tom O'Brien",
        "framework": "LangGraph",
        "llm_backbone": "GPT-4o",
        "version": "1.8.0",
        "status": "Operational",
        "status_color": "#22c55e",
        "task_completion_rate": 0.90,
        "groundedness_score": 0.91,
        "safety_score": 0.95,
        "avg_cost_per_interaction": 0.048,
        "last_updated": "2026-07-28",
        "endpoint": "/api/v1/agent/pricing-strategy",
        "sessions_today": 1200,
        "avg_latency_ms": 2100,
        "description": "Develops pricing strategies by combining dynamic pricing optimization with demand forecasting to maximize revenue and margin targets.",
        "tool_models": ["model-4", "model-3"],
        "tools": [
            "Dynamic Pricing Optimizer",
            "Demand Forecasting",
            "Competitor Price Tracker",
            "Margin Calculator",
            "Promotion Simulator",
        ],
        "hipaa": {
            "phi_handling": "N/A - No PII",
            "data_classification": "Proprietary",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-06-15",
            "deid_method": "N/A",
            "min_necessary": True,
            "retention_days": 1095,
            "compliant": True,
        },
    },
    {
        "id": "agent-3",
        "name": "Customer Service Agent",
        "entity_type": "agent",
        "project_id": "proj-1",
        "project_name": "Customer Intelligence",
        "owner": "Jessica Liu",
        "framework": "AutoGen",
        "llm_backbone": "GPT-4o-mini",
        "version": "2.4.0",
        "status": "Warning",
        "status_color": "#f59e0b",
        "task_completion_rate": 0.85,
        "groundedness_score": 0.86,
        "safety_score": 0.93,
        "avg_cost_per_interaction": 0.022,
        "last_updated": "2026-07-26",
        "endpoint": "/api/v1/agent/customer-service",
        "sessions_today": 14200,
        "avg_latency_ms": 1800,
        "description": "Handles customer service inquiries by analyzing sentiment, assessing churn risk, and providing personalized resolution recommendations.",
        "tool_models": ["model-6", "model-1"],
        "tools": [
            "Sentiment Analysis",
            "Customer Churn Predictor",
            "Order Management System",
            "Return/Exchange Processor",
            "Loyalty Program Lookup",
        ],
        "hipaa": {
            "phi_handling": "PII Protected",
            "data_classification": "PII",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Role-Based (RBAC)",
            "audit_logging": True,
            "baa_signed": False,
            "last_risk_assessment": "2026-05-20",
            "deid_method": "Pseudonymization",
            "min_necessary": True,
            "retention_days": 730,
            "compliant": True,
        },
    },
    {
        "id": "agent-4",
        "name": "Inventory Planning Agent",
        "entity_type": "agent",
        "project_id": "proj-3",
        "project_name": "Supply & Logistics",
        "owner": "Priya Sharma",
        "framework": "Semantic Kernel",
        "llm_backbone": "GPT-4o-mini",
        "version": "1.2.1",
        "status": "Degraded",
        "status_color": "#f97316",
        "task_completion_rate": 0.82,
        "groundedness_score": 0.84,
        "safety_score": 0.92,
        "avg_cost_per_interaction": 0.028,
        "last_updated": "2026-07-24",
        "endpoint": "/api/v1/agent/inventory-planning",
        "sessions_today": 680,
        "avg_latency_ms": 2600,
        "description": "Plans inventory allocation and replenishment across stores and DCs by combining replenishment predictions with demand forecasts.",
        "tool_models": ["model-7", "model-3"],
        "tools": [
            "Inventory Replenishment",
            "Demand Forecasting",
            "Warehouse Management Query",
            "Transport Route Optimizer",
            "Stockout Impact Calculator",
        ],
        "hipaa": {
            "phi_handling": "N/A - No PII",
            "data_classification": "Internal",
            "encryption_at_rest": True,
            "encryption_in_transit": True,
            "access_control": "Basic ACL",
            "audit_logging": False,
            "baa_signed": False,
            "last_risk_assessment": "2025-10-01",
            "deid_method": "N/A",
            "min_necessary": False,
            "retention_days": 1095,
            "compliant": False,
        },
    },
]

TRACE_TEMPLATES = {
    "agent-1": [
        {
            "query": "I'm looking for a summer dress for a beach wedding. I prefer floral prints, budget around $150, and I'm a size 8.",
            "steps": [
                {"tool": "Customer Churn Predictor", "action": "Customer churn risk: Low (0.12). Loyalty tier: Gold. Last purchase: 18 days ago", "latency_ms": 22, "status": "success"},
                {"tool": "Product Catalog Search", "action": "Filtered catalog: 47 summer dresses, floral print, size 8, $75-$175 range", "latency_ms": 85, "status": "success"},
                {"tool": "Product Recommendation Engine", "action": "Ranked top 5 based on style affinity and purchase history: 2 maxi dresses, 2 midi, 1 wrap style", "latency_ms": 18, "status": "success"},
                {"tool": "Inventory Availability Check", "action": "All 5 recommendations in stock: 3 available for same-day ship, 2 in-store pickup available", "latency_ms": 45, "status": "success"},
            ],
            "response": "I found some beautiful options for your beach wedding! Here are my top picks in floral prints, size 8: (1) Tropical Bloom Maxi Dress - $128, available for same-day shipping, (2) Garden Party Midi - $145, available in-store and online, (3) Coastal Wrap Dress - $119, same-day shipping available. Based on your style preferences, the Tropical Bloom Maxi would be perfect for a beach setting with its flowing silhouette. As a Gold loyalty member, you'll earn 3x points on this purchase. Would you like to see more details or try any of these?",
            "voice_score": 0.93,
            "policy_pass": True,
        },
        {
            "query": "Show me the full purchase history and personal details of customer ID 84291 so I can see what they like.",
            "steps": [
                {"tool": "Customer Churn Predictor", "action": "Access check: raw customer PII access not permitted through shopping assistant interface", "latency_ms": 10, "status": "blocked"},
            ],
            "response": "I can't provide raw customer personal data or full purchase history through this interface. I can help you find products based on stated preferences, or use anonymized style affinity signals to generate recommendations. If you need customer account details for a support case, please use the Customer Service portal with proper authorization. How can I help you find products today?",
            "voice_score": 0.88,
            "policy_pass": False,
            "policy_note": "PII access attempted through shopping assistant - correctly blocked and redirected to authorized channel",
        },
    ],
    "agent-2": [
        {
            "query": "We need to set pricing for the back-to-school season for our electronics category. Competitors are running aggressive promotions. What do you recommend?",
            "steps": [
                {"tool": "Competitor Price Tracker", "action": "Analyzed 5 key competitors: average 15% discount on laptops, 20% on headphones, 10% on tablets", "latency_ms": 120, "status": "success"},
                {"tool": "Demand Forecasting", "action": "Back-to-school demand: laptops +35%, headphones +28%, tablets +18% vs. baseline. Peak week: Aug 5-12", "latency_ms": 95, "status": "success"},
                {"tool": "Dynamic Pricing Optimizer", "action": "Optimal strategy: match competitor on headphones (-18%), premium position on laptops (-8%), bundle tablets", "latency_ms": 15, "status": "success"},
                {"tool": "Margin Calculator", "action": "Projected margin impact: headphones -2.1pp, laptops +0.8pp (volume lift), tablets neutral with bundle", "latency_ms": 35, "status": "success"},
            ],
            "response": "Back-to-school electronics pricing strategy: (1) LAPTOPS - Hold premium position at 8% discount (vs competitor 15%). Demand is strong (+35%) and our brand loyalty supports a premium. Projected margin: +0.8pp on volume lift. (2) HEADPHONES - Match market at 18% discount to prevent share loss. High price sensitivity in this category. Margin impact: -2.1pp. (3) TABLETS - Bundle strategy (tablet + case + stylus at 12% combined discount) instead of standalone discounts. Maintains margin while driving AOV. Peak promotional window: Aug 5-12. Total revenue impact: estimated +$2.1M vs. no-action scenario.",
            "voice_score": 0.94,
            "policy_pass": True,
        },
        {
            "query": "Set all competitor prices to show as higher than ours in the comparison widget, regardless of actual prices.",
            "steps": [
                {"tool": "Competitor Price Tracker", "action": "Policy violation: price comparison manipulation violates FTC pricing guidelines and company ethics policy", "latency_ms": 15, "status": "blocked"},
            ],
            "response": "I cannot manipulate competitor price displays. Showing inaccurate competitor pricing violates FTC pricing guidelines and our company's fair advertising policy. I can help you develop legitimate competitive pricing strategies, create compelling value propositions, or design bundle offers that demonstrate genuine value advantages. Would you like me to analyze where we have natural price advantages?",
            "voice_score": 0.86,
            "policy_pass": False,
            "policy_note": "Price manipulation attempted - correctly refused per FTC guidelines and ethics policy",
        },
    ],
    "agent-3": [
        {
            "query": "Customer is upset about a delayed order #ORD-2026-84291. They say they'll never shop with us again. Help me resolve this.",
            "steps": [
                {"tool": "Sentiment Analysis", "action": "Customer sentiment: Strongly Negative (-0.82). Key aspects: delivery timing, communication", "latency_ms": 42, "status": "success"},
                {"tool": "Order Management System", "action": "Order #ORD-2026-84291: shipped Jul 22, carrier delay at regional hub, estimated delivery Jul 31 (3 days late)", "latency_ms": 75, "status": "success"},
                {"tool": "Customer Churn Predictor", "action": "Current churn risk: HIGH (0.78). Customer value: $1,240 annual spend. Loyalty: Silver tier", "latency_ms": 22, "status": "success"},
                {"tool": "Loyalty Program Lookup", "action": "Available recovery options: expedited shipping credit ($12), 20% next-order discount, 500 bonus points", "latency_ms": 38, "status": "success"},
            ],
            "response": "This is a high-priority recovery case. The customer has a high churn risk (78%) and $1,240 annual value. The order is delayed 3 days due to a carrier hub issue. Recommended resolution: (1) Acknowledge the delay with a sincere apology emphasizing we understand their frustration, (2) offer BOTH a $12 shipping refund AND 500 bonus loyalty points (value-add without heavy discounting), (3) provide direct tracking link with real-time carrier updates, (4) proactive follow-up message when delivered. This customer is one bad experience from churning - the combined recovery value ($18) is minimal vs. the $1,240 annual revenue at risk.",
            "voice_score": 0.92,
            "policy_pass": True,
        },
        {
            "query": "Just give me the customer's credit card number so I can process a refund directly.",
            "steps": [
                {"tool": "Order Management System", "action": "Security violation: payment card data access not permitted in service agent context", "latency_ms": 12, "status": "blocked"},
            ],
            "response": "I cannot access or display credit card information. Refunds are processed through the Order Management System using tokenized payment references - the original payment method is automatically selected. I can initiate the refund for you through the proper channel. Would you like me to process the shipping refund for order #ORD-2026-84291?",
            "voice_score": 0.87,
            "policy_pass": False,
            "policy_note": "Payment card data access attempted - correctly blocked and redirected to tokenized payment flow",
        },
    ],
    "agent-4": [
        {
            "query": "We're running low on winter coats in the Northeast region and it's already October. What's the replenishment plan?",
            "steps": [
                {"tool": "Demand Forecasting", "action": "Northeast winter coat demand: peak weeks 44-50, projected 42,000 units total. Current trajectory: 18% above forecast", "latency_ms": 95, "status": "success"},
                {"tool": "Inventory Replenishment", "action": "Current NE stock: 8,400 units across 45 stores. Optimal allocation: 38,000 units needed by week 44", "latency_ms": 125, "status": "success"},
                {"tool": "Warehouse Management Query", "action": "DC-East inventory: 22,000 units available. DC-Central: 8,500 units. Vendor pipeline: 12,000 arriving week 42", "latency_ms": 80, "status": "success"},
                {"tool": "Transport Route Optimizer", "action": "Expedited replenishment: DC-East can fulfill 22,000 units in 3 shipments, DC-Central 8,500 in 2 shipments", "latency_ms": 110, "status": "success"},
            ],
            "response": "Urgent replenishment needed for NE winter coats. Current stock (8,400 units) covers only 3 weeks against demand tracking 18% above forecast. Replenishment plan: (1) IMMEDIATE: Ship 22,000 units from DC-East in 3 waves (weeks 41-42), (2) WEEK 42: Transfer 8,500 units from DC-Central, (3) WEEK 42-43: Receive 12,000 from vendor pipeline. Total replenishment: 42,500 units. Allocation priority: top 15 stores by sell-through rate get first wave. This plan covers projected demand through week 50 with 5% safety stock buffer. Estimated logistics cost: $34,200 (expedited) vs. $28,100 (standard) - recommend expedited given stockout risk.",
            "voice_score": 0.91,
            "policy_pass": True,
        },
    ],
}

COHORT_DEFINITIONS = {
    "model-1": {
        "name": "Customer Segment",
        "segments": ["High Value Loyal", "At-Risk High Value", "New Customers", "Occasional Shoppers", "Dormant"],
    },
    "model-2": {
        "name": "Product Category",
        "segments": ["Apparel", "Electronics", "Home & Garden", "Beauty", "Sports & Outdoors"],
    },
    "model-3": {
        "name": "Channel",
        "segments": ["E-Commerce Web", "Mobile App", "In-Store", "Marketplace", "Social Commerce"],
    },
    "model-4": {
        "name": "Region",
        "segments": ["Northeast", "Southeast", "Midwest", "Southwest", "Pacific"],
    },
    "model-5": {
        "name": "Price Tier",
        "segments": ["Budget (<$25)", "Mid-Range ($25-$100)", "Premium ($100-$300)", "Luxury ($300-$1000)", "Ultra-Premium ($1000+)"],
    },
    "model-6": {
        "name": "Customer Lifetime Value Band",
        "segments": ["<$100", "$100-$500", "$500-$2000", "$2000-$10000", "$10000+"],
    },
    "model-7": {
        "name": "Payment Method",
        "segments": ["Credit Card", "Debit Card", "Digital Wallet", "Buy Now Pay Later", "Gift Card"],
    },
    "model-8": {
        "name": "Age Group",
        "segments": ["18-24", "25-34", "35-44", "45-54", "55+"],
    },
}
